/*
 * To change this template), choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.sat.siat.cob.seguimiento.dto.stdcob.enums;

/**
 *
 * @author root
 */
public enum CampoEnum {

    ID_DATASOURCE_SGT("sgt"),
    ID_TIPO_DOCUMENTO_FIELD("IDTIPODOCUMENTO"),
    ID_TIPO_FIRMA_FIELD("IDFIRMATIPO"),
    ID_VALOR_BOOLEAN_FIELD("IDVALORBOOLEAN"),
    ID_TIPO_MEDIO_FIELD("IDTIPOMEDIO"),
    ID_MODALIDAD_DOCUMENTO_FIELD("IDMODALIDADDOCUMENTO"),
    ID_ETAPA_VIGILANCIA_FIELD("IDETAPAVIGILANCIA"),
    ID_ESTADO_VIGILANCIA_FIELD("IDESTADOVIGILANCIA"),
    ID_OBLIGACION_SANCION_FIELD("IDOBLIGACION"),
    ID_OBLIGACION_FIELD("IDOBLIGACION"),
    ID_PLANTILLA_FIELD("IDPLANTILLA"),
    ID_TRANSICION("IDTRANSICION"),
    ID_ESTADO_DOCTO_FIELD("IDESTADODOCTO"),
    ID_CAUSA_CANCELA_DOCTO_FIELD("IDCAUSACANCEL"),
    ID_TRANSICION_DOCTO_FIELD("IDTRANSICIONDOCTO"),
    ID_PERIODICIDAD_FIELD("IDPERIODICIDAD"),
    ID_PERIODO_FIELD("IDPERIODO"),
    ID_NOMBRE_FIELD("NOMBRE"),
    ID_SANCION_FIELD("SANCION"),
    ID_DESCRIPCION_FIELD("DESCRIPCION"),
    ID_EJERCICIO_FISCAL_FIELD("IDEJERCICIOFISCAL"),
    ID_TIPO_DOCUMENTO("SGTC_TIPODOCUMENTO"),
    ID_TIPO_FIRMA("ADMC_FIRMATIPO"),
    ID_VALOR_BOOLEAN("SGTC_VALORBOOLEAN"),
    ID_TIPO_MEDIO("SGTC_TIPOMEDIO"),
    ID_MODALIDAD_DOCUMENTO("SGTC_MODALIDADDOC"),
    ID_ETAPA_VIGILANCIA("SGTC_ETAPAVIG"),
    ID_ESTADO_VIGILANCIA("SGTC_ESTADOVIG"),
    ID_OBLISANCION("SGTC_OBLISANCION"),
    ID_OBLIGACION("SGTC_OBLIGACION"),
    ID_PLANTILLA("SGTC_PLANTILLA"),
    ID_TRANSICION_SGT("SGTC_TRANSICIONSGT"),
    ID_ESTADO_DOCUMENTO("SGTC_ESTADODOCTO"),
    ID_CAUSA_CANCEL_DOCUMENTO("SGTC_CAUSACANCELDOC"),
    ID_TRANSICION_DOCUMENTO("SGTC_TRANSICIONDOC"),
    ID_PERIODICIDAD("SGTC_PERIODICIDAD"),
    ID_PERIODO("SGTC_PERIODO"),
    ID_EJERCICIO_FISCAL("SGTC_EJERCICIOFISCAL"),
    ID_TIPO_DOCUMENTO_PLANTILLA("T_CATTIPODOCUMENTOPLANTILLA"),
    ID_DATASOURCE_ARCA("T"),
    ID_TIPO_DOCUMENTO_PLANTILLA_FIELD("IDTIPODOCUMENTOPLANTILLA"),
    DESCRIPCION_TABLE("SGTC_DSCRIPCIONVIG"),
    CAMPO_DESCRIPCION_FIELD("IDDESCRIPCION"),
    NIVELEMI_TABLE("SGTC_NIVELEMISION"),
    ID_NIVELEMI_FIELD("IDNIVELEMISION"),
    CARGOADMN_TABLE("SGTC_CARGOADMTVO"),
    ID_CARGOADMN_FIELD("idcargoadmtvo"),
    REGIMEN_TABLE("RFCC_REGIMEN"),
    ID_REGIMEN_FIELD("idregimen"),
    REGIMEN_DESC_FIELD("descorta"),
    MOTIVORENUENTE_TABLE("SGTC_MTVONORENUENT"),
    ID_MOTIVORENUENTE_FIELD("IDMOTIVONORENUENTE");
    

    private String nombre;

    private CampoEnum(String nombre) {
        this.nombre = nombre;
    }

    public String getNombre() {
        return nombre;
    }
}
