package mx.gob.sat.siat.cob.seguimiento.dao.catalogos.sql;

public interface MultaDescuentoSQL {
    String OBTEN_TODAS_MULTAS_MONTO = "SELECT SGTC_MULTADSCUENTO.*, SGTC_MULTACOB.NOMBREMULTACOB as RESOLDESCR, " + 
    "cbzc_multaDscuento.nombre as MULTADESCUENTO FROM SGTC_MULTADSCUENTO " + 
    "INNER JOIN SGTC_MULTACOB  ON SGTC_MULTACOB.CONSTANTERESOLMOTIVO = SGTC_MULTADSCUENTO.CONSTANTERESOLMOTIVO " + 
    "INNER JOIN cbzc_multaDscuento ON cbzc_multaDscuento.IDMULTADSCUENTO = SGTC_MULTADSCUENTO.idmultadescuento " + 
    "AND SGTC_MULTADSCUENTO.FECHAFIN IS NULL order by SGTC_MULTADSCUENTO.IDMULTAMONTODTO desc";
    
    String AGREGA_MULTAS_MONTO ="INSERT INTO SGTC_MULTADSCUENTO (CONSTANTERESOLMOTIVO, FECHAINICIO, FECHAFIN, " +
        "IDMULTADESCUENTO, IDMULTAMONTODTO)  VALUES(:idResolMotivo, :fechaInicio, :fechaFin, :multaDes, SGTQ_MULTADSCUENTO.nextval)";
    
    String UPDATE_MULTAS_MONTO ="UPDATE SGTC_MULTADSCUENTO set FECHAFIN= :fechaFin where IDMULTAMONTODTO= :idMultaMonto";  
           
    String BUSCA_MULTAS_MONTO_REPETIDA = "SELECT COUNT(*) REGISTROS FROM SGTC_MULTADSCUENTO WHERE CONSTANTERESOLMOTIVO = ? AND FECHAFIN IS NULL "; 
    
    String BUSCA_ID_MONTO_REPETIDA = "SELECT SGTC_MULTADSCUENTO.IDMULTAMONTODTO as ID FROM SGTC_MULTADSCUENTO WHERE CONSTANTERESOLMOTIVO = ? AND FECHAFIN IS NULL "; 
        
        
    String LISTA_COMBO_MULTA_DESCUENTO = "select  o.IDMULTADSCUENTO as ID, o.NOMBRE as DESCRIPCION  from cbzc_multaDscuento o  WHERE o.FECHAFIN IS NULL";
    
}
