package mx.gob.sat.siat.cob.seguimiento.dao.catalogos.sql;

public interface UsuarioEFSQL {

    String OBTEN_TODOS_USUARIOSEF = "SELECT U.USUARIO, U.IDENTIDADFEDERATIVA, U.NOMBREUSUARIO, E.DESCRIPCION AS ENTIDADDESC, "
            + " U.FECHAINICIO, U.FECHAFIN, U.CORREOELECTRONICO "
            + " FROM SGTP_USUARIOEF U "
            + " INNER JOIN RFCC_ENTIDADFEDERA E on E.NUMEROENTIDAD = U.IDENTIDADFEDERATIVA "
            + " order by U.FECHAINICIO desc ";
    String OBTEN_TODOS_USUARIOSEF_POR_VIGILANCIA = "SELECT U.USUARIO, U.IDENTIDADFEDERATIVA, U.NOMBREUSUARIO, Ee.DESCRIPCION AS ENTIDADDESC,  "
            + "U.FECHAINICIO, U.FECHAFIN, U.CORREOELECTRONICO  "
            + "FROM SGTP_USUARIOEF U  "
            + "INNER JOIN sgtt_vigilanciaEf E on E.IDENTIDADFEDERATIVA = U.IDENTIDADFEDERATIVA  "
            + "INNER JOIN RFCC_ENTIDADFEDERA Ee on ee.NUMEROENTIDAD = e.IDENTIDADFEDERATIVA "
            + "and e.idvigilancia = ? "
            + "and u.fechafin is null "
            + "order by U.FECHAINICIO desc";
    String AGREGA_USUARIOEF = "INSERT INTO SGTP_USUARIOEF (USUARIO, IDENTIDADFEDERATIVA, "
            + "NOMBREUSUARIO, FECHAINICIO, FECHAFIN, CORREOELECTRONICO) "
            + "VALUES(?, ?, ?, ?, ?, ?)";
    String EDITA_USUARIOEF = "UPDATE SGTP_USUARIOEF SET IDENTIDADFEDERATIVA =? , NOMBREUSUARIO =? ,"
            + "CORREOELECTRONICO =? WHERE USUARIO = ?";
    String ELIMINA_USUARIOEF = "UPDATE SGTP_USUARIOEF SET FECHAFIN = ? WHERE USUARIO = ?";
    String BUSCA_USUARIOEF_POR_ID = "SELECT * FROM SGTP_USUARIOEF WHERE USUARIO =?";
    String BUSCA_USUARIOEF_POR_IDYNOM = "SELECT COUNT(*) REGISTROS FROM SGTP_USUARIOEF WHERE USUARIO= ? ";
    String BUSCA_USUARIOEF_POR_RFCCORTO = "select u.usuario, u.identidadfederativa, u.nombreusuario, "
            + "u.fechainicio, u.fechafin, u.correoelectronico, e.descripcion as nombreentidad "
            + "from SGTP_USUARIOEF U INNER JOIN RFCC_ENTIDADFEDERA E on E.NUMEROENTIDAD = U.IDENTIDADFEDERATIVA "
            + "WHERE U.USUARIO=? AND U.FECHAFIN IS NULL";
    String REACTIVA_USUARIOEF = "UPDATE SGTP_USUARIOEF SET FECHAFIN = NULL WHERE USUARIO = ?";
    String BUSCA_USUARIOS_POR_ENTIDAD = "select * from SGTP_USUARIOEF WHERE identidadfederativa= ? AND FECHAFIN IS NULL ";
}
