package mx.gob.sat.siat.cob.seguimiento.dao.arca.sql;

import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.enums.TipoDocumentoEnum;

/**
 *
 * @author Juan
 */
public interface DoctoEnviaArcaSQL {

    String CONSTANTE_RESOLMOTIVO_IS_NULL = " AND plantilla.constanteResolMotivo IS NULL\n";
    String PLANTILLA_ES_MULTA_CERO = "    AND plantilla.esMulta = 0 \n";
    String PLANTILLA_ES_MULTA_UNO = "    AND plantilla.esMulta = 1 \n";
    String JOIN_PLANTILLA_BACK = " JOIN SGTT_PlantillaBack plantilla\n"
            + "    ON plantilla.idTipoDocumento = vigilancia.idTipoDocumento\n"
            + "    AND plantilla.idEtapaVigilancia = docto.idEtapaVigilancia\n"
            + "    AND plantilla.idTipoMEdio = vigilancia.idTipoMedio\n"
            + "    AND plantilla.idTipoFirma = vigilancia.idTipoFirma\n"
            + "    AND plantilla.idNivelEmision = vigilancia.idNivelEmision\n"
            + "    AND plantilla.idCargoAdmtvo = vigilancia.idCargoAdmtvo\n"
            + "    AND plantilla.dias IS NULL\n"
            + "    AND plantilla.fechafin IS NULL \n";
    String JOIN_DOCUMENTO = "JOIN sgtt_documento docto\n"
            + "    ON vigilancia.idvigilancia = docto.idvigilancia \n"
            + "    AND vigilancia.idVigilancia = #{jobParameters['idVigilancia']}  \n"
            + "    AND docto.idAdmonLocal = '#{jobParameters['idAdmonLocal']}'  \n"
            + "    AND docto.ultimoestado = 1\n"
            + "    AND vigilancia.idTipoDocumento !=4\n"
            + "    AND docto.idEtapaVigilancia !=4\n";
    /**
     * Consulta para mandar de COB/IDC - ARCA (Archivos)
     */
    String SELECT_DOCUMENTO_IDC_CARGA_ARCHIVOS = "SELECT /*+DRIVING_SITE(persona)*/  \n"
            + "  docto.boid AS BoId,\n"
            + "  docto.numerocontrol AS idDocumento,  \n"
            + "  docto.numerocontrolpadre AS numeroControlPadre,    \n"
            + "  tipoDocto.idTipoDocumentoArca AS idTipoDocto_ARCA,\n"
            + "  tipoMedio.idmedioenvioarca AS idMedioEnvio_ARCA,\n"
            + "  0 AS idEstadoDeDocumento,\n"
            + "  plantilla.idPlantillaArca AS idDocumentoPlantilla,\n"
            + "  domicilio.codigoPostal AS codPostal,\n"
            + "  docto.idCRH AS CRH,\n"
            + "  docto.idAdmonLocal AS ALSC,\n"
            + "  docto.IdTipoPersona AS idTipoPersona,\n"
            + "  vigilancia.IdNivelEmision as IdFirmaDigitalAplicable,\n"
            + "  a.nombreFuncionario AS NombreFuncionario,\n"
            + "  a.descripcionCargo AS DescripcionFuncionario,\n"
            + "  vigilancia.IdNivelEmision as IdFirmaDigitalAplicable,\n"
            + "  to_char(env.fechaEnvioArca,'yyyy-mm-dd hh24:mi:ss') AS fechaRegistroArca, \n"
            + "  null AS importe,\n"
            + "  null AS resolucion,\n"
            + "  null AS idResolucion,\n"
            + "  null AS idProceso,\n"
            + "  null AS idSubProceso,\n"
            + "  null AS idLote,\n"
            + " #{jobParameters['camposFirmaDigital']}"
            + "  domicilio.NOMBREVIALIDAD AS Calle,\n"
            + "  domicilio.NUMEROEXTERIOR AS NumeroExterior,\n"
            + "  domicilio.NUMEROINTERIOR AS NumeroInterior,\n"
            + "  domicilio.ENTREVIALIDAD1 AS EntreCalle1,\n"
            + "  domicilio.ENTREVIALIDAD2 AS EntreCalle2,\n"
            + "  domicilio.REFERENCIAS AS ReferenciaAdicionales, \n"
            + "  entidadFed.DESCRIPCION AS DescripcionEntidadFederativa,\n"
            + "  colonia.COLONIA AS DescripcionColonia,\n"
            + "  localidad.localidad AS DescripcionLocalidad,\n"
            + "  municipio.municipio AS DescripcionMunicipio,\n"
            + "  pf.curp AS CURP,\n"
            + "  pf.nombre AS nombre,\n"
            + "  pf.apellidopaterno AS apPaterno,\n"
            + "  pf.apellidomaterno AS apMaterno,\n"
            + "  pm.razonSocial || ' ' || catalogo.descorta AS compania,\n"
            + "  nvl(pf.RFC, pm.RFC) as RFC_Vigente,\n"
            + "  vigilancia.idVigilancia\n"
            + "FROM  sgtt_vigilancia vigilancia \n"
            + JOIN_DOCUMENTO
            + " #{jobParameters['joinFirmaDigital']}"
            + "  JOIN sgtc_tipomedio tipoMedio\n"
            + "    ON tipoMedio.idTipoMedio = vigilancia.idTipoMedio\n"
            + "  JOIN sgtc_tipodocumento tipoDocto\n"
            + "    ON tipoDocto.idTipoDocumento = vigilancia.idTipoDocumento\n"
            + "     join sgtt_enviodocsarca env\n"
            + "      on docto.idVigilancia = env.idVigilancia\n"
            + "      AND docto.idAdmonLocal = env.idAdmonLocal\n"
            + "      AND env.esEnvioResoluciones = 0"
            + JOIN_PLANTILLA_BACK
            + CONSTANTE_RESOLMOTIVO_IS_NULL
            + PLANTILLA_ES_MULTA_CERO
            + "  JOIN rfcp_persona persona\n"
            + "     ON persona.idPersona=docto.boid\n"
            + "  LEFT JOIN RFCP_PERSONAFISICA pf\n"
            + "     ON persona.idPersona = pf.idPersona\n"
            + " LEFT JOIN RFCP_PERSONAMORAL pm\n"
            + "    on persona.idPersona = pm.idPersona \n"
            + " LEFT JOIN rfcc_catalogo catalogo\n"
            + "    on pm.idregimencapital = catalogo.idcatalogo\n"
            + " LEFT JOIN (RFCP_DOMICILIO domicilio\n"
            + "  LEFT JOIN RFCC_ENTIDADFEDERA entidadFed\n"
            + "   ON entidadFed.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "  LEFT JOIN RFCC_COLONIA colonia       \n"
            + "   ON colonia.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "   AND colonia.IDMUNICIPIO = domicilio.IDMUNICIPIO\n"
            + "   AND colonia.IDCOLONIA = domicilio.IDCOLONIA\n"
            + "  LEFT JOIN RFCC_LOCALIDAD localidad\n"
            + "   ON localidad.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "   AND localidad.IDMUNICIPIO = domicilio.IDMUNICIPIO\n"
            + "   AND localidad.IDLOCALIDAD = domicilio.IDLOCALIDAD\n"
            + "  LEFT JOIN RFCC_MUNICIPIO municipio\n"
            + "   ON municipio.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED \n"
            + "   AND municipio.IDMUNICIPIO = domicilio.IDMUNICIPIO)\n"
            + "   ON persona.idpersona = domicilio.IDPERSONA \n"
            + " #{jobParameters['joinNivelEmision']}"
            + " where\n"
            + "   domicilio.IDTIPODOMICILIO = '32'\n"
            + "   AND (domicilio.FECHAFINVIGENCIA > SYSDATE OR domicilio.FECHAFINVIGENCIA IS NULL) \n"
            + "   AND (domicilio.FECHACREACION = \n"
            + "    (SELECT MAX (B2S1.FECHACREACION)\n"
            + "     FROM RFCP_DOMICILIO B2S1\n"
            + "     WHERE B2S1.IDPERSONA = domicilio.IDPERSONA\n"
            + "   AND B2S1.IDTIPODOMICILIO = '32'\n"
            + "   AND B2S1.FECHAINICIOVIGENCIA <= SYSDATE\n"
            + "   AND (B2S1.FECHAFINVIGENCIA > SYSDATE OR B2S1.FECHAFINVIGENCIA IS NULL)) OR domicilio.FECHAMODIFICACION IS NULL)\n"
            + "   AND(catalogo.fechafinvigencia > SYSDATE OR catalogo.fechafinvigencia IS NULL)\n";
    /**
     * Consulta para mandar Obligacion_Periodo de COB - ARCA (Archivos)
     */
    String SELECT_OBLIGACION_PERIODO_CARGA_ARCHIVOS = "SELECT docto.numeroControl AS idDocumento, \n"
            + "  periodicidad.descripcionPeriodo AS descripcionPeriodo,\n"
            + "  detalleDocto.ejercicio AS ejercicio,\n"
            + "  obligacion.concepto AS conceptoImpuesto,\n"
            + "  obligacion.descripcion AS descripcionObligacion,\n"
            + "  fundamento.fundamentolegal AS fundamentoLegal,\n"
            + " detalleDocto. fechaVencimientoobligacion AS fechaVencimiento,\n"
            + "  null AS sancion,\n"
            + "  null AS infraccion,\n"
            + "  null AS importe,\n"
            + "  null AS idObligacion,\n"
            + "  null AS constanteResolMotivo,\n"
            + "  null AS idPeriodo,\n"
            + "  null AS idPeriodicidad,\n"
            + "  null AS fechaNotificacion\n"
            + "FROM (\n"
            + "  SELECT docto.NumeroControl\n"
            + "  FROM sgtt_vigilancia vigilancia\n"
            + JOIN_DOCUMENTO
            + JOIN_PLANTILLA_BACK
            + CONSTANTE_RESOLMOTIVO_IS_NULL
            + PLANTILLA_ES_MULTA_CERO
            + ") docto\n"
            + "  INNER JOIN sgtt_detalledoc detalleDocto\n"
            + "    ON docto.numerocontrol = detalleDocto.numerocontrol\n"
            + "    AND detalleDocto.idSituacionICEP = 0\n"
            + "  INNER JOIN sgtc_obligacion obligacion\n"
            + "    ON obligacion.idObligacion = detalleDocto.idObligacion\n"
            + "  INNER JOIN sgta_periodicidad periodicidad\n"
            + "    ON periodicidad.idperiodo = detalleDocto.idperiodo \n"
            + "    AND periodicidad.idperiodicidad = detalleDocto.idperiodicidad\n"
            + "  LEFT JOIN sgtc_FundamentoLeg fundamento\n"
            + "    ON fundamento.idObligacion = detalleDocto.idObligacion\n"
            + "    AND fundamento.idEjercicioFiscal = detalleDocto.ejercicio\n"
            + "    AND fundamento.idPeriodicidad = detalleDocto.idperiodicidad\n"
            + "    AND fundamento.idPeriodo = detalleDocto.idperiodo\n"
            + "    AND fundamento.idRegimen = detalleDocto.idRegimen\n"
            + "    AND fundamento.fechaFin IS NULL";
    /**
     * Select Requerimientos Anteriores de COB a ARCA (Archivos)
     */
    String SELECT_REQANTERIORES_COB = "SELECT docto.numeroControl AS IdDocumento, \n"
            + "  docto.numeroControlPadre AS IdDocumentoPadre,\n"
            + "  sgta_tde.NombreDocumentoEtapa AS fcDescripcionTipoDeReq, \n"
            + "  docto.fechaNotificacion AS fdFechaDeNotificacion,\n"
            + "  sgtc_o.descripcion AS fcDescripcionDeObligacion, \n"
            + "  sgta_p.descripcionPeriodo AS fcDescripcionDePeriodo, \n"
            + "  sgtt_dd.ejercicio AS fiEjercicio,\n"
            + "  sgtt_dd.fechaCumplimiento AS fdFechaDePresDeObligacion, \n"
            + "  docto.fechavencimientodocto AS fdFechaDeVencDeRequerimiento,\n"
            + "  sgtc_sicep.Nombre AS fcEstadoDeObligDeVenc\n"
            + "FROM (\n"
            + "  SELECT docto.numerocontrol, docto.idEtapaVigilancia, docto.idVigilancia, "
            + " docto.fechaVencimientoDocto, docto.fechaNotificacion, docto.numeroControlPadre\n"
            + "  FROM sgtt_documento docto\n"
            + "    WHERE level > 1\n"
            + "    start with docto.numerocontrol in ( \n"
            + "              SELECT docto.numerocontrol \n"
            + "              FROM sgtt_vigilancia vigilancia\n"
            + JOIN_DOCUMENTO
            + "                 AND docto.idEtapaVigilancia in (2,3)"
            + JOIN_PLANTILLA_BACK + CONSTANTE_RESOLMOTIVO_IS_NULL + PLANTILLA_ES_MULTA_CERO + ")\n"
            + "    connect by docto.numerocontrol = prior docto.numerocontrolpadre\n"
            + "    ) docto\n"
            + "  INNER JOIN sgtt_vigilancia vigilancia\n"
            + "          ON vigilancia.idvigilancia = docto.idvigilancia\n"
            + "          AND vigilancia.idVigilancia = '234'\n"
            + "  INNER JOIN sgtt_detalledoc sgtt_dd\n"
            + "    ON(docto.numerocontrol = sgtt_dd.numerocontrol)\n"
            + "  INNER JOIN sgtc_obligacion sgtc_o\n"
            + "   ON (sgtt_dd.idobligacion = sgtc_o.idobligacion)\n"
            + "  INNER JOIN sgta_periodicidad sgta_p\n"
            + "    ON sgta_p.idperiodo = sgtt_dd.idperiodo \n"
            + "    AND sgta_p.idperiodicidad = sgtt_dd.idperiodicidad\n"
            + "  INNER JOIN SGTA_TipoDocEtapa sgta_tde\n"
            + "    ON sgta_tde.IdTipoDocumento = vigilancia.idTipoDocumento\n"
            + "    AND sgta_tde.IdEtapaVigilancia = docto.idEtapaVigilancia\n"
            + "  INNER JOIN SGTC_SituacionICEP sgtc_sicep\n"
            + "   ON sgtc_sicep.IdSituacionICEP = sgtt_dd.IdSituacionICEP";
    /*
     * Select datos para mandar de COB - ARCA (Multas) sin join cobranza proceso b
     */
    String SELECT_DOCUMENTOS_MULTAS_CREDITO = "select /*+DRIVING_SITE(persona) index_ss(detalleDocto) index_ss(multaObli)*/ \n"
            + "docto.boid AS boid,\n"
            + "null AS numeroControlPadre,\n"
            + "multaDocto.numeroResolucion AS idDocumento,\n"
            + "15  AS idTipoDocto_ARCA,\n"
            + "tipoMedio.idmedioenvioarca AS idMedioEnvio_ARCA,\n"
            + "0 AS idEstadoDeDocumento, \n"
            + "plantilla.idPlantillaArca AS idDocumentoPlantilla,\n"
            + "multaDocto.idAdmonLocalorigen AS ALSC,\n"
            + "multaDocto.idResolucion AS idResolucion,\n"
            + "domicilio.codigoPostal AS codPostal,\n"
            + "multaDocto.idCRHActual AS CRH,\n"
            + "docto.IdTipoPersona AS idTipoPersona,\n"
            + "null AS resolucion,\n"
            + "vigilancia.IdNivelEmision as IdFirmaDigitalAplicable,\n"
            + "a.nombreFuncionario AS NombreFuncionario,\n"
            + "a.descripcionCargo AS DescripcionFuncionario,\n"
            + "multaDocto.monto AS importe,\n"
            + "docto.idVigilancia,\n"
            + "multaDocto.numeroLoteCbz as idLote,\n"
            + "multaDocto.numeroProcesoCbz as idProceso,\n"
            + "multaDocto.numeroEtapaCbz as idSubProceso,\n"
            + "#{jobParameters['camposFirmaDigital']}"
            + "domicilio.NOMBREVIALIDAD AS Calle,\n"
            + "domicilio.NUMEROEXTERIOR AS NumeroExterior,\n"
            + "domicilio.NUMEROINTERIOR AS NumeroInterior,\n"
            + "domicilio.ENTREVIALIDAD1 AS EntreCalle1,\n"
            + "domicilio.ENTREVIALIDAD2 AS EntreCalle2,\n"
            + "domicilio.REFERENCIAS AS ReferenciaAdicionales, \n"
            + "entidadFed.DESCRIPCION AS DescripcionEntidadFederativa,\n"
            + "colonia.COLONIA AS DescripcionColonia,\n"
            + "localidad.localidad AS DescripcionLocalidad,\n"
            + "municipio.municipio AS DescripcionMunicipio,\n"
            + "pf.curp AS CURP,\n"
            + "pf.nombre AS nombre,\n"
            + "pf.apellidopaterno AS apPaterno,\n"
            + "pf.apellidomaterno AS apMaterno,\n"
            + "pm.razonSocial || ' ' || catalogo.descorta AS compania,\n"
            + "nvl(pf.RFC, pm.RFC) AS rfc,\n"
            + "multaDocto.fechaRegistro AS fechaDocumento,\n"
            + "env.fechaEnvioArca AS fechaEnvioARCA, \n"
            + "to_char(env.fechaEnvioArca,'yyyy-mm-dd hh24:mi:ss') AS fechaRegistroArca, \n"
            + "30 AS idEstatus, \n"
            + "multaDocto.constanteResolMotivo AS idMotivo, \n"
            + "municipio.CLAVEENTIDADFED AS idEntidadFederativa,\n"
            + "municipio.IDMUNICIPIO AS idDelegacionMunicipio\n"
            + "FROM sgtt_documento docto\n"
            + "    INNER JOIN SGTT_ResolucionDoc multaDocto\n"
            + "      ON multaDocto.numerocontrol = docto.numerocontrol\n"
            + "      AND multaDocto.ultimoestado = 2\n"
            + "      AND docto.idVigilancia = #{jobParameters['idVigilancia']}\n"
            + "      AND multaDocto.idAdmonLocalorigen = '#{jobParameters['idAdmonLocal']}'\n"
            + "      AND multaDocto.monto is not null\n"
            + " #{jobParameters['joinFirmaDigital']}"
            + "  INNER JOIN sgtt_vigilancia vigilancia\n"
            + "      ON vigilancia.idvigilancia = docto.idvigilancia\n"
            + "    JOIN sgtc_tipomedio tipoMedio\n"
            + "      ON tipoMedio.idTipoMedio = vigilancia.idTipoMedio\n"
            + "     join sgtt_enviodocsarca env\n"
            + "      on docto.idVigilancia = env.idVigilancia\n"
            + "      AND multaDocto.idAdmonLocalorigen = env.idAdmonLocal\n"
            + "      AND env.esEnvioResoluciones = 1\n"
            + JOIN_PLANTILLA_BACK
            + "AND plantilla.constanteResolMotivo = multadocto.constanteResolMotivo\n"
            + PLANTILLA_ES_MULTA_UNO
            + "JOIN rfcp_persona persona\n"
            + "ON persona.idPersona=docto.boid  \n"
            + "LEFT JOIN RFCP_PERSONAFISICA pf\n"
            + "ON persona.idPersona = pf.idPersona   \n"
            + "LEFT JOIN RFCP_PERSONAMORAL pm\n"
            + "on persona.idPersona = pm.idPersona \n"
            + "LEFT JOIN rfcc_catalogo catalogo\n"
            + "on pm.idregimencapital = catalogo.idcatalogo\n"
            + "LEFT JOIN (RFCP_DOMICILIO domicilio\n"
            + "LEFT JOIN RFCC_ENTIDADFEDERA entidadFed\n"
            + "ON entidadFed.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "LEFT JOIN RFCC_COLONIA colonia       \n"
            + "ON colonia.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "AND colonia.IDMUNICIPIO = domicilio.IDMUNICIPIO\n"
            + "AND colonia.IDCOLONIA = domicilio.IDCOLONIA\n"
            + "LEFT JOIN RFCC_LOCALIDAD localidad\n"
            + "ON localidad.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "AND localidad.IDMUNICIPIO = domicilio.IDMUNICIPIO\n"
            + "AND localidad.IDLOCALIDAD = domicilio.IDLOCALIDAD\n"
            + "LEFT JOIN RFCC_MUNICIPIO municipio\n"
            + "ON municipio.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED \n"
            + "AND municipio.IDMUNICIPIO = domicilio.IDMUNICIPIO)\n"
            + "ON persona.idpersona = domicilio.IDPERSONA \n"
            + "#{jobParameters['joinNivelEmision']}\n"
            + "WHERE domicilio.IDTIPODOMICILIO = '32'\n"
            + "AND (domicilio.FECHAFINVIGENCIA > SYSDATE OR domicilio.FECHAFINVIGENCIA IS NULL) \n"
            + "AND (domicilio.FECHACREACION = \n"
            + "(SELECT MAX (B2S1.FECHACREACION)\n"
            + "FROM RFCP_DOMICILIO B2S1\n"
            + "WHERE B2S1.IDPERSONA = domicilio.IDPERSONA\n"
            + "AND B2S1.IDTIPODOMICILIO = '32'\n"
            + "AND B2S1.FECHAINICIOVIGENCIA <= SYSDATE\n"
            + "AND (B2S1.FECHAFINVIGENCIA > SYSDATE OR B2S1.FECHAFINVIGENCIA IS NULL)) OR domicilio.FECHAMODIFICACION IS NULL)\n"
            + "AND(catalogo.fechafinvigencia > SYSDATE OR catalogo.fechafinvigencia IS NULL)";
    /*
     * Select datos para mandar de COB - ARCA (Multas)
     * TODO: Debe de quedar a lo mas parecido a SELECT_DOCUMENTOS_MULTAS_CREDITO
     */
    String SELECT_DOCUMENTOS_MULTAS = "select /*+DRIVING_SITE(persona) index_ss(detalleDocto) index_ss(multaObli)*/ distinct\n"
            + "  docto.boid AS boid,\n"
            + "  null AS numeroControlPadre,  \n"
            + "  multaDocto.numeroResolucion AS idDocumento,\n"
            + "  15  AS idTipoDocto_ARCA,\n"
            + "  tipoMedio.idmedioenvioarca AS idMedioEnvio_ARCA,\n"
            + "  0 AS idEstadoDeDocumento,\n"
            + "  plantilla.idPlantillaArca AS idDocumentoPlantilla,\n"
            + "  multaDocto.idAdmonLocalOrigen AS ALSC,\n"
            + "  resolucion.idResolucion AS idResolucion,\n"
            + "  docto.rfc AS rfc,\n"
            + "  domicilio.codigoPostal AS codPostal,\n"
            + "  multaDocto.idCRHActual AS CRH,\n"
            + "  docto.IdTipoPersona AS idTipoPersona,\n"
            + "  null AS resolucion,\n"
            + "  vigilancia.IdNivelEmision as IdFirmaDigitalAplicable,\n"
            + "  a.nombreFuncionario AS NombreFuncionario,\n"
            + "  a.descripcionCargo AS DescripcionFuncionario,\n"
            + "  multaDocto.monto AS importe,\n"
            + "  null AS idProceso,\n"
            + "  null AS idSubProceso,\n"
            + "  null AS idLote,\n"
            + "  domicilio.NOMBREVIALIDAD AS Calle,\n"
            + "  domicilio.NUMEROEXTERIOR AS NumeroExterior,\n"
            + "  domicilio.NUMEROINTERIOR AS NumeroInterior,\n"
            + "  domicilio.ENTREVIALIDAD1 AS EntreCalle1,\n"
            + "  domicilio.ENTREVIALIDAD2 AS EntreCalle2,\n"
            + "  entidadFed.DESCRIPCION AS DescripcionEntidadFederativa,\n"
            + "  colonia.COLONIA AS DescripcionColonia,\n"
            + "  localidad.localidad AS DescripcionLocalidad,\n"
            + "  municipio.municipio AS DescripcionMunicipio,\n"
            + "  pf.curp AS CURP,\n"
            + "  pf.nombre AS nombre,\n"
            + "  pf.apellidopaterno AS apPaterno,\n"
            + "  pf.apellidomaterno AS apMaterno,\n"
            + "  pm.razonSocial || ' ' || pm.descorta AS compania,\n"
            + "  nvl(pf.RFC, pm.RFC) AS RFC_Vigente\n"
            + "from sgtt_ResolucionDoc multaDocto\n"
            + "  inner join SGTA_ResolICEP multaIcep \n"
            + "    on multaIcep.numeroResolucion = multaDocto.numeroResolucion \n"
            + "    and multaDocto.ultimoestado = 2 \n"
            + "    and multaDocto.idresolucion is null\n"
            + "  inner join SGTT_DetalleDoc detalleDocto \n"
            + "    on detalleDocto.numeroControl = multaIcep.numeroControl \n"
            + "    and detalleDocto.claveIcep = multaIcep.claveIcep\n"
            + "    AND detalleDocto.idSituacionICEP = 0\n"
            + "  inner join SGTC_MultaMonto multaObli \n"
            + "    on multaObli.IdObligacion = detalleDocto.IdObligacion \n"
            + "    and multaObli.constanteResolMotivo = multaDocto.constanteResolMotivo\n"
            + "    AND multaObli.fechaFin is null\n"
            + "  inner join sgtc_obligacion obl \n"
            + "    on obl.idObligacion = detalleDocto.idObligacion\n"
            + "  inner join SGTT_Documento docto \n"
            + "    on docto.numeroControl = detalleDocto.numeroControl\n"
            + "  inner join sgtt_vigilancia vigilancia\n"
            + "    on vigilancia.idvigilancia = docto.idvigilancia\n"
            + "    and vigilancia.idVigilancia = '#{jobParameters['idVigilancia']}'\n"
            + "    and docto.idAdmonLocal = '#{jobParameters['idAdmonLocal']}'\n"
            + "  join cbzt_resolucion resolucion \n"
            + "      on resolucion.numresoluciondet = multaDocto.numeroResolucion\n"
            + "      and resolucion.escargamasiva = 1\n"
            + "    join cbzc_unidadadmva ua \n"
            + "      on resolucion.idaudeterminante = ua.idunidadadmva \n"
            + "      and ua.idunidadmvatipo = 15\n"
            + "  INNER JOIN sgtc_tipomedio tipoMedio\n"
            + "    ON tipoMedio.idTipoMedio = vigilancia.idTipoMedio\n"
            + "  inner join sgtc_multadscuento descuento\n"
            + "    on descuento.constanteresolmotivo = multaDocto.constanteresolmotivo \n"
            + "    and descuento.fechafin is null\n"
            + JOIN_PLANTILLA_BACK
            + CONSTANTE_RESOLMOTIVO_IS_NULL
            + PLANTILLA_ES_MULTA_UNO
            + "  JOIN rfcp_persona persona\n"
            + "      ON persona.idPersona=docto.boid\n"
            + "  LEFT JOIN RFCP_PERSONAFISICA pf\n"
            + "      on persona.idPersona = pf.idPersona\n"
            + "  LEFT JOIN \n"
            + "    (SELECT \n"
            + "        pm.idPersona, \n"
            + "        pm.rfc, \n"
            + "        pm.razonSocial, \n"
            + "        catalogo.fechaFinVigencia, \n"
            + "        catalogo.descorta \n"
            + "       FROM RFCP_PERSONAMORAL pm\n"
            + "         JOIN rfcc_catalogo catalogo\n"
            + "           ON pm.idregimencapital = catalogo.idcatalogo\n"
            + "    ) pm\n"
            + "    on persona.idPersona = pm.idPersona \n"
            + "  LEFT JOIN (RFCP_DOMICILIO domicilio\n"
            + "    LEFT JOIN RFCC_ENTIDADFEDERA entidadFed\n"
            + "      ON entidadFed.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "    LEFT JOIN RFCC_COLONIA colonia    \n"
            + "      ON colonia.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "      AND colonia.IDMUNICIPIO = domicilio.IDMUNICIPIO\n"
            + "      AND colonia.IDCOLONIA = domicilio.IDCOLONIA\n"
            + "    LEFT JOIN RFCC_LOCALIDAD localidad\n"
            + "      ON localidad.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "      AND localidad.IDMUNICIPIO = domicilio.IDMUNICIPIO\n"
            + "      AND localidad.IDLOCALIDAD = domicilio.IDLOCALIDAD\n"
            + "    LEFT JOIN RFCC_MUNICIPIO municipio\n"
            + "      ON municipio.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED \n"
            + "      AND municipio.IDMUNICIPIO = domicilio.IDMUNICIPIO\n"
            + "  )\n"
            + "  ON persona.idpersona = domicilio.IDPERSONA \n"
            + "    #{jobParameters['joinNivelEmision']} \n"
            + " WHERE \n"
            + "  (multaObli.constanteResolMotivo in ('RESOLMOTIVO_INCUMPLIMIENTO','RESOLMOTIVO_AMBOS') \n"
            + "  and (docto.fechaNotificacion >= multaObli.fechaInicio)\n"
            + "  and (docto.fechaNotificacion <= multaObli.fechaFin or multaObli.fechaFin is null)\n"
            + "  or(multaObli.constanteResolMotivo = 'RESOLMOTIVO_EXTEMPORANEIDAD' \n"
            + "    and (detalleDocto.fechaCumplimiento >= multaObli.fechaInicio)\n"
            + "    and (detalleDocto.fechaCumplimiento <= multaObli.fechaFin or multaObli.fechaFin is null)\n"
            + "  )\n"
            + "  or(multaObli.constanteResolMotivo = 'RESOLMOTIVO_COMPLEMENTARIA' \n"
            + "    and (detalleDocto.fechaPresentacionCompl >= multaObli.fechaInicio)\n"
            + "    and (detalleDocto.fechaPresentacionCompl <= multaObli.fechaFin or multaObli.fechaFin is null)\n"
            + "  ))\n"
            + "  AND domicilio.IDTIPODOMICILIO = '32'\n"
            + "  AND (domicilio.FECHAFINVIGENCIA > SYSDATE OR domicilio.FECHAFINVIGENCIA IS NULL) \n"
            + "  AND domicilio.FECHAMODIFICACION = \n"
            + "    (SELECT MAX (B2S1.FECHAMODIFICACION)\n"
            + "    FROM RFCP_DOMICILIO B2S1\n"
            + "    WHERE B2S1.IDPERSONA = domicilio.IDPERSONA\n"
            + "      AND B2S1.IDTIPODOMICILIO = '32'\n"
            + "      AND B2S1.FECHAINICIOVIGENCIA <= SYSDATE\n"
            + "      AND (B2S1.FECHAFINVIGENCIA > SYSDATE OR B2S1.FECHAFINVIGENCIA IS NULL)\n"
            + "    )\n"
            + "  AND(pm.fechafinvigencia > SYSDATE OR pm.fechafinvigencia IS NULL)";
    /*
     * Select datos para mandar Obligaciones y Periodos de COB - ARCA (Multas)
     */
    String SELECT_OBLIGACION_PERIODO_MULTA = "    SELECT\n"
            + "  multaDocto.numeroResolucion AS idDocumento, \n"
            + "  periodicidad.descripcionPeriodo AS descripcionPeriodo,\n"
            + "  detalleDocto.ejercicio AS ejercicio,\n"
            + "  detalleDocto.idobligacion AS idObligacion,\n"
            + "  multaDocto.constanteresolmotivo AS constanteResolMotivo,\n"
            + "  detalleDocto.idperiodo AS idPeriodo,\n"
            + "  detalleDocto.idperiodicidad AS idPeriodicidad, \n"
            + "  detalleDocto.numerocontrol AS numeroControl, \n"
            + "  docto.fechanotificacion AS fechaNotificacion,\n"
            + "  obligacion.concepto AS conceptoImpuesto,\n"
            + "  obligacion.descripcion AS descripcionObligacion,\n"
            + "  fundamento.fundamentolegal AS fundamentoLegal,\n"
            + "  docto.fechavencimientodocto AS fechaVencimiento,\n"
            + "  multaMonto.sancion AS sancion,\n"
            + "  multaMonto.infraccion AS infraccion,\n"
            + "  multaMonto.descripcionMonto AS importe,\n"
            + "  docto.numeroControl\n"
            + "FROM sgtt_documento docto\n"
            + "  INNER JOIN SGTT_ResolucionDoc multaDocto\n"
            + "    ON multaDocto.numerocontrol = docto.numerocontrol\n"
            + "    AND multaDocto.ultimoestado = 2\n"
            + "    AND docto.idVigilancia = #{jobParameters['idVigilancia']}\n"
            + "    AND multaDocto.idAdmonLocalorigen = '#{jobParameters['idAdmonLocal']}'\n"
            + "  INNER JOIN sgtt_detalledoc detalleDocto\n"
            + "    ON detalleDocto.numerocontrol = docto.numerocontrol\n"
            + "INNER JOIN sgtt_vigilancia vigilancia\n"
            + "    ON vigilancia.idvigilancia = docto.idvigilancia\n"
            + "  inner join sgta_resolIcep resolucion\n"
            + "    on resolucion.numeroResolucion = multaDocto.numeroResolucion\n"
            + "    and resolucion.claveIcep = detalleDocto.claveIcep\n"
            + "    and resolucion.numeroControl = detalleDocto.numeroControl\n"
            + "    and resolucion.idMultaMonto is not null\n"
            + "  INNER JOIN sgtc_obligacion obligacion\n"
            + "    ON obligacion.idObligacion = detalleDocto.idObligacion\n"
            + "  INNER JOIN SGTC_MULTAMONTO multaMonto\n"
            + "    ON multaMonto.idMultaMonto = resolucion.idMultaMonto\n"
            + "  INNER JOIN sgta_periodicidad periodicidad\n"
            + "    ON periodicidad.idperiodo = detalleDocto.idperiodo \n"
            + "    AND periodicidad.idperiodicidad = detalleDocto.idperiodicidad\n"
            + "  LEFT JOIN sgtc_FundamentoLeg fundamento\n"
            + "    ON fundamento.idObligacion = detalleDocto.idObligacion\n"
            + "    AND fundamento.idRegimen = detalleDocto.idRegimen\n"
            + "    AND fundamento.idEjercicioFiscal = detalleDocto.ejercicio\n"
            + "    AND fundamento.idPeriodicidad = detalleDocto.idperiodicidad\n"
            + "    AND fundamento.idPeriodo = detalleDocto.idperiodo\n"
            + "    AND fundamento.fechafin IS NULL"
            + JOIN_PLANTILLA_BACK
            + "    AND plantilla.constanteResolMotivo = multadocto.constanteResolMotivo\n"
            + PLANTILLA_ES_MULTA_UNO;
    /*
     * Origen Multa  COB - ARCA (Multas)
     **/
    String SELECT_ORIGEN_MULTA = "SELECT DISTINCT multaDocto.numeroResolucion AS idDocumento, \n"
            + "    doc_origen.numerocontrol AS numeroControlOrigen,\n"
            + "    doc_origen.fechaNotificacion AS fechaNotificacionOrigen,\n"
            + "    doc_primero.numerocontrol numeroControlPrimero,\n"
            + "    doc_primero.fechaNotificacion AS fechaNotificacionPrimero,\n"
            + "    doc_segundo.numerocontrol AS numeroControlSegundo,\n"
            + "    doc_segundo.fechaNotificacion AS fechaNotificacionSegundo\n"
            + " FROM SGTT_ResolucionDoc multaDocto\n"
            + "JOIN SGTA_ResolICEP multaIcep \n"
            + "  ON multaDocto.NumeroResolucion = multaIcep.numeroResolucion\n"
            + "  AND multaDocto.ultimoestado = 2\n"
            + "  AND multaDocto.idresolucion IS NULL\n"
            + "JOIN SGTT_DetalleDoc detalleDocto \n"
            + "  ON multaIcep.numeroControl = detalleDocto.numeroControl \n"
            + "  AND multaIcep.claveIcep = detalleDocto.claveICEP \n"
            + "  AND detalleDocto.idSituacionICEP = 0\n"
            + "inner join sgtt_documento doc_origen\n"
            + "  ON multaDocto.numeroControl = doc_origen.numeroControl\n"
            + "join cbzt_resolucion resolucion \n"
            + "   on resolucion.numresoluciondet = doc_origen.numeroControl\n"
            + "   and resolucion.escargamasiva = 1\n"
            + "join cbzc_unidadadmva ua \n"
            + "   on resolucion.idaudeterminante = ua.idunidadadmva \n"
            + "   and ua.idunidadmvatipo = 15 \n"
            + "  INNER JOIN sgtt_vigilancia vigilancia\n"
            + "    ON vigilancia.idvigilancia = doc_origen.idvigilancia\n"
            + "    AND vigilancia.idVigilancia = '#{jobParameters['idVigilancia']}' \n"
            + "    AND doc_origen.idAdmonLocal = '#{jobParameters['idAdmonLocal']}' \n"
            + "  INNER JOIN sgtc_tipomedio tipoMedio\n"
            + "    ON tipoMedio.idTipoMedio = vigilancia.idTipoMedio\n"
            + "  INNER JOIN sgtc_multaMonto multaObli\n"
            + "    ON multaObli.idObligacion = detalleDocto.idObligacion \n"
            + "    AND multaObli.fechaFin is null\n"
            + JOIN_PLANTILLA_BACK
            + CONSTANTE_RESOLMOTIVO_IS_NULL
            + PLANTILLA_ES_MULTA_UNO
            + "  LEFT JOIN sgtt_Documento doc_primero \n"
            + "    ON doc_primero.numerocontrolpadre = doc_origen.numerocontrol   \n"
            + "  LEFT JOIN sgtt_Documento doc_segundo \n"
            + "    ON doc_segundo.numerocontrolpadre = doc_primero.numerocontrol\n"
            + "  WHERE doc_origen.numerocontrolpadre IS NULL";
    /*
     * Origen Multa  COB - ARCA (Multas) sin join cobranza (proceso b)
     **/
    String SELECT_ORIGEN_MULTA_CREDITO = "select  \n"
            + "  origen.numeroResolucion AS idDocumento, \n"
            + "  origen.numerocontrol AS numeroControlOrigen,\n"
            + "  docto.fechaNotificacion AS fechaNotificacionOrigen,\n"
            + "  vigilancia.idTipoDocumento,\n"
            + "  docto.idEtapaVigilancia,\n"
            + "  primera.numerocontrol numeroControlPrimero,\n"
            + "  primera.fechaNotificacion AS fechaNotificacionPrimero,\n"
            + "  segunda.numerocontrol AS numeroControlSegundo,\n"
            + "  segunda.fechaNotificacion AS fechaNotificacionSegundo\n"
            + "from sgtt_resolucionDoc origen\n"
            + "  join sgtt_documento docto\n"
            + "    ON origen.numeroControl = docto.numeroControl\n"
            + "    and origen.ultimoEstado = 2\n"
            + "    AND origen.monto is not null\n"
            + "  JOIN sgtt_vigilancia vigilancia\n"
            + "    ON vigilancia.idvigilancia = docto.idvigilancia\n"
            + "    AND vigilancia.idVigilancia = #{jobParameters['idVigilancia']}\n"
            + "    AND origen.idAdmonLocalorigen = '#{jobParameters['idAdmonLocal']}' "
            + JOIN_PLANTILLA_BACK
            + "    AND plantilla.constanteResolMotivo = origen.constanteResolMotivo\n"
            + PLANTILLA_ES_MULTA_UNO
            + "left join (\n"
            + "         select \n"
            + "          numeroControl,\n"
            + "          numeroControlPadre,\n"
            + "          fechaNotificacion\n"
            + "       from sgtt_documento\n"
            + "        WHERE idVigilancia = #{jobParameters['idVigilancia']}\n"
            + "             AND idEtapaVigilancia = 2\n"
            + "         ) segunda\n"
            + "    on segunda.numeroControl = docto.numeroControlPadre AND docto.idEtapaVigilancia = 3\n"
            + "  left join (\n"
            + "         select \n"
            + "          numeroControl,\n"
            + "          numeroControlPadre,\n"
            + "          fechaNotificacion\n"
            + "        from sgtt_documento\n"
            + "        WHERE idVigilancia = #{jobParameters['idVigilancia']} \n"
            + "             AND idEtapaVigilancia = 1\n"
            + "         ) primera\n"
            + "    on (docto.idEtapaVigilancia = 3 AND primera.numeroControl = segunda.numeroControlPadre) \n"
            + "    OR (docto.idEtapaVigilancia = 2 AND primera.numeroControl = docto.numeroControlPadre)";
    /*
     * Bitacora Resolucion
     */
    String INSERT_BITACORA_RESOLUCION = "insert into sgtb_sgtresolucion (idEstadoResolucion,"
            + "fechamovimiento, numeroResolucion)"
            + "values (3, sysdate, :id)";
    /*
     * Origen Multa  
     **/
    String SELECT_ORIGEN_MULTA_ANTECESOR = "SELECT NumeroControl, FechaNotificacion, NumeroControlPadre, level\n"
            + " FROM siat_sgt.sgtt_Documento\n"
            + " start with NumeroControlPadre = \'?\' "
            + " connect by NumeroControl = prior NumeroControlPadre\n"
            + "order by level\n";
    String SELECT_ORIGEN_MULTA_ANTECESOR2 = "SELECT doc.numerocontrol as NumeroControl, doc.fechanotificacion as FechaNotificacion, tipo.nombre as Nombre, doc.numerocontrolpadre as NumeroControlPadre, level\n"
            + " from sgtt_documento doc, sgtt_vigilancia vig, sgtc_tipodocumento tipo \n"
            + " where vig.idvigilancia = doc.idvigilancia \n"
            + " and tipo.idtipodocumento = vig.idtipodocumento\n"
            + " and level > 1\n"
            + " start with doc.numerocontrol = ? \n"
            + " connect by doc.numerocontrol = prior doc.numerocontrolpadre\n"
            + "order by level\n";
    String SELECT_ORIGEN_MULTA_POSTERIORES = "SELECT doc.numerocontrol as NumeroControl, doc.fechanotificacion as FechaNotificacion, tipo.nombre as Nombre, doc.numerocontrolpadre as NumeroControlPadre, level\n"
            + " from sgtt_documento doc, sgtt_vigilancia vig, sgtc_tipodocumento tipo \n"
            + " where vig.idvigilancia = doc.idvigilancia \n"
            + " and tipo.idtipodocumento = vig.idtipodocumento \n"
            + " and level > 1\n"
            + " start with doc.numerocontrol = ? \n"
            + " connect by doc.numerocontrolpadre = prior doc.numerocontrol\n"
            + "order by level\n";
    /*
     * Proceso para generar multas (Rodrigo)
     */
    String DETALLE_MULTA_ARCA = "SELECT obligacion.idObligacion,\n"
            + "  detalleDocto.idRegimen,\n"
            + "  detalleDocto.claveIcep,\n"
            + "  docto.numerocontrol as iddocumento, \n"
            + "  periodicidad.descripcionPeriodo as descripcionPeriodicidad, \n"
            + "  detalleDocto.ejercicio as ejercicio,\n"
            + "  obligacion.concepto as conceptoImpuesto,\n"
            + "  obligacion.descripcion as descripcionObligacion,\n"
            + "  periodo.descripcion as descripcionPeriodo,\n"
            + "  fundamentolegal as fundamentoLegal,\n"
            + "  docto.fechavencimientodocto as fechaVencimiento,\n"
            + "  sancion.sancion as sancion,\n"
            + "  sancion.infraccion as infraccion,\n"
            + "  multa.monto as importe\n"
            + "FROM sgtt_documento docto\n"
            + "  INNER JOIN sgtt_detalledoc detalleDocto\n"
            + "    ON (docto.numerocontrol = detalleDocto.numerocontrol\n"
            + "      AND docto.numerocontrol = ?\n"
            + "      AND detalleDocto.claveICEP IN (replaceSQL)\n"
            + "      )\n"
            + "  INNER JOIN sgtc_periodo periodo\n"
            + "    ON periodo.idperiodo = detalleDocto.idperiodo\n"
            + "  INNER JOIN sgtc_obligacion obligacion\n"
            + "    ON (obligacion.idObligacion = detalleDocto.idObligacion\n"
            + "      AND obligacion.fechafin IS NULL)\n"
            + "  INNER JOIN sgta_periodicidad periodicidad\n"
            + "    ON periodicidad.idperiodo = detalleDocto.idperiodo \n"
            + "    AND periodicidad.idperiodicidad = detalleDocto.idperiodicidad\n"
            + "  INNER JOIN sgtc_multamonto multa\n"
            + "    ON  (multa.idObligacion = obligacion.idObligacion\n"
            + "      AND multa.fechafin IS NULL)\n"
            + "      \n"
            + "  INNER JOIN sgtc_obliSancion sancion\n"
            + "    ON (sancion.idObligacion = obligacion.idObligacion\n"
            + "      AND sancion.fechafin IS NULL)";
    String SELECT_MULTA_DOCTO = "SELECT docto.boid as boid,\n"
            + "  docto.numerocontrol as idDocumento,\n"
            + "  docto.numerocontrolpadre as numeroControlPadre,  \n"
            + TipoDocumentoEnum.MULTA + "  as idTipoDocto_ARCA,\n"
            + "  tipoMedio.idmedioenvioarca as idMedioEnvio_ARCA,\n"
            + "  docto.ultimoEstado as idEstadoDeDocumento,\n"
            + "  docto.rfc as rfc,\n"
            + "  plantilla.idPlantillaArca as idDocumentoPlantilla,\n"
            + "  null AS importe,\n"
            + "  multaDocto.numeroResolucion AS resolucion,\n"
            + "  multaDocto.idResolucion AS idResolucion,\n"
            + "  Z.SAT_REGION_CD AS ClaveALR,\n"
            + "  A.SAT_ADDRESS AS Calle,\n"
            + "  A.ADDRESS4 AS NumeroExterior,\n"
            + "  A.COUNTY AS NumeroInterior,\n"
            + "  D.DESCR50 AS DescripcionColonia,\n"
            + "  E.DESCR50 AS DescripconLocalidad,\n"
            + "  A.ADDRESS2 AS EntreCalle1,\n"
            + "  A.ADDRESS3 AS EntreCalle2,\n"
            + "  F.DESCR50 AS DescripcionMunicipio,\n"
            + "  C.DESCR AS DescripcionEntidadFederativa,\n"
            + "  A.POSTAL AS CodigoPostal,\n"
            + "  Y.DESCR AS ClaveCRH,\n"
            + "  BNAME.FIRST_NAME AS nombre,\n"
            + "  BNAME.LAST_NAME AS apPaterno,\n"
            + "  BNAME.SECOND_LAST_NAME AS apMaterno,\n"
            + "  PNID.NATIONAL_ID AS CURP,\n"
            + "  CORP.DESCR50 AS compania\n"
            + "FROM sgtt_documento docto\n"
            + "  INNER JOIN siat_sgt.sgtt_detalledoc detalleDocto\n"
            + "    ON (docto.numerocontrol = detalleDocto.numerocontrol \n"
            + "      AND detalleDocto.IDSITUACIONICEP = 0\n"
            + "      AND docto.numerocontrol = ?\n"
            + "      )\n"
            + "  INNER JOIN sgtt_resoluciondoc multaDocto\n"
            + "    ON (multaDocto.numeroControl = docto.numeroControl\n"
            + "      AND multaDocto.esCancelada = 0 \n"
            + "      AND multaDocto.idResolucion = ?\n"
            + "    )\n"
            + "  INNER JOIN sgtt_vigilancia vigilancia\n"
            + "    ON (vigilancia.idvigilancia = docto.idvigilancia)\n"
            + "  INNER JOIN sgtc_tipomedio tipoMedio\n"
            + "    ON (tipoMedio.idTipoMedio = vigilancia.idTipoMedio)\n"
            + "  INNER JOIN sgtt_plantillaarca plantilla\n"
            + "    ON(plantilla.idTipoDocumento = vigilancia.idTipoDocumento\n"
            + "      AND plantilla.idEtapaVigilancia = docto.idEtapaVigilancia\n"
            + "      AND plantilla.esPLantillaDIOT = vigilancia.esObligacionDIOT\n"
            + "      AND plantilla.idTipoMEdio = vigilancia.idTipoMedio\n"
            + "      AND plantilla.idTipoFirma = vigilancia.idTipoFirma\n"
            + "      AND plantilla.idModalidadDocumento = vigilancia.idModalidadDocumento\n"
            + "      AND plantilla.constanteResolMotivo = multaDocto.ConstanteResolMotivo)\n"
            + "  INNER JOIN PS_BO_CM_USE BB \n"
            + "    ON (docto.boid = BB.BO_ID\n"
            + "      AND BB.PRIMARY_IND = 'Y' \n"
            + "      AND BB.CM_USE_START_DT <= SYSDATE \n"
            + "      AND (BB.CM_USE_END_DT > SYSDATE OR BB.CM_USE_END_DT IS NULL) \n"
            + "      AND (BB.ROLE_TYPE_ID = 2 OR BB.ROLE_TYPE_ID = 9))\n"
            + "  INNER JOIN PS_BO_CM B \n"
            + "    ON (B.BO_ID = BB.BO_ID \n"
            + "      AND B.PROFILE_CM_SEQ = BB.PROFILE_CM_SEQ \n"
            + "      AND B.CM_PURPOSE_TYPE_ID = '32' \n"
            + "      AND B.CM_TYPE_ID = '1' \n"
            + "      AND (B.BO_CM_END_DT > SYSDATE OR B.BO_CM_END_DT IS NULL)\n"
            + "      AND B.BO_CM_START_DT <= SYSDATE)\n"
            + "  INNER JOIN  PS_CM A \n"
            + "    ON (A.CM_ID = B.CM_ID AND A.CM_TYPE_ID = B.CM_TYPE_ID)\n"
            + "  INNER JOIN PS_STATE_TBL C \n"
            + "    ON (C.STATE = A.STATE \n"
            + "      AND C.COUNTRY = A.COUNTRY\n"
            + "      AND A.COUNTRY = 'MEX')  \n"
            + "  LEFT JOIN PS_SAT_COLONY_TBL D \n"
            + "    ON (D.COUNTRY = A.COUNTRY \n"
            + "      AND D.STATE= A.STATE \n"
            + "      AND D.SAT_MUNICIPALITY = A.SAT_MUNICIPALITY\n"
            + "      AND D.SAT_COLONY_CD = A.SAT_COLONY_CD) \n"
            + "  LEFT JOIN PS_SAT_TOWN_TBL E \n"
            + "    ON(E.STATE = A.STATE  \n"
            + "      AND E.SAT_MUNICIPALITY = A.SAT_MUNICIPALITY \n"
            + "      AND E.SAT_TOWN_CODE = A.SAT_TOWN_CODE     \n"
            + "      AND E.COUNTRY = A.COUNTRY)   \n"
            + "  LEFT JOIN PS_SAT_MUNICIP_TBL F \n"
            + "    ON (F.STATE = A.STATE \n"
            + "      AND F.SAT_MUNICIPALITY = A.SAT_MUNICIPALITY \n"
            + "      AND F.COUNTRY = A.COUNTRY) \n"
            + "  INNER JOIN PS_SAT_RB_REGION X \n"
            + "    ON (X.REGION_ID = A.REGION_ID) \n"
            + "  INNER JOIN PS_RB_REGION Y \n"
            + "    ON (Y.REGION_ID = X.REGION_ID \n"
            + "      AND Y.REGION_CATEGORY = X.REGION_CATEGORY AND Y.REGION_TYPE = 'CRH') \n"
            + "  INNER JOIN (SELECT \n"
            + "      A.REGION_ID, \n"
            + "      A.SAT_REGION_CD \n"
            + "    FROM\n"
            + "      PS_SAT_RB_REGION A, \n"
            + "      PS_RB_REGION     B \n"
            + "    WHERE \n"
            + "      A.REGION_ID = B.REGION_ID \n"
            + "      AND A.REGION_CATEGORY = B.REGION_CATEGORY \n"
            + "      AND    B.REGION_TYPE  = 'ALR')Z\n"
            + "    ON (Z.REGION_ID = Y.PARENT_REGION_ID)\n"
            + "  LEFT JOIN PS_RD_PERSON PERSON \n"
            + "    ON (docto.boid = PERSON.bo_id \n"
            + "      AND rownum = 1)\n"
            + "  LEFT JOIN PS_BO_NAME BNAME \n"
            + "    ON (PERSON.bo_id = BNAME.bo_id \n"
            + "      AND BNAME.NAME_TYPE   = 'PREFERRED' \n"
            + "      AND BNAME.PRIMARY_IND = 'Y' \n"
            + "      AND ROWNUM = 1)\n"
            + "  LEFT JOIN PS_RD_PERS_NID PNID \n"
            + "    ON (PNID.PERSON_ID = PERSON.PERSON_ID \n"
            + "      AND PNID.NATIONAL_ID_TYPE = 'CURP' \n"
            + "      AND ROWNUM = 1)\n"
            + "  LEFT JOIN PS_RD_COMPANY COMP \n"
            + "    ON (docto.boid = COMP.bo_id \n"
            + "      AND rownum = 1) \n"
            + "  LEFT JOIN PS_SAT_CORP_TYPE CORP \n"
            + "    ON (CORP.SETID = 'SATCR' \n"
            + "      AND CORP.SAT_CORP_TYPE = COMP.SAT_CORP_TYPE \n"
            + "      AND ROWNUM = 1)              \n"
            + "GROUP BY\n"
            + "  docto.boid ,\n"
            + "  docto.numerocontrol ,\n"
            + "  docto.numerocontrolpadre ,  \n"
            + TipoDocumentoEnum.MULTA + ",\n"
            + "  tipoMedio.idmedioenvioarca ,\n"
            + "  docto.ultimoEstado ,\n"
            + "  docto.rfc ,\n"
            + "  plantilla.idPlantillaArca ,\n"
            + "  null ,\n"
            + "  multaDocto.numeroResolucion ,\n"
            + "  multaDocto.idResolucion ,\n"
            + "  Z.SAT_REGION_CD ,\n"
            + "  A.SAT_ADDRESS ,\n"
            + "  A.ADDRESS4 ,\n"
            + "  A.COUNTY,\n"
            + "  D.DESCR50,\n"
            + "  E.DESCR50,\n"
            + "  A.ADDRESS2,\n"
            + "  A.ADDRESS3,\n"
            + "  F.DESCR50,\n"
            + "  C.DESCR,\n"
            + "  A.POSTAL,\n"
            + "  Y.DESCR,\n"
            + "  BNAME.FIRST_NAME,\n"
            + "  BNAME.LAST_NAME,\n"
            + "  BNAME.SECOND_LAST_NAME,\n"
            + "  PNID.NATIONAL_ID,\n"
            + "  CORP.DESCR50";
}