/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.sat.siat.cob.seguimiento.dao.stdcob.sql;

/**
 *
 * @author root
 */
public interface ArchivoDiligenciaSQL {
    
         String BUSCA_ARCHIVO_POR_NOMYENTIDAD = "SELECT R.IDENTIDADFEDERATIVA, R.NOMBREARCHIVOCARGA, R.TOTALREGISTROSARCHIVOCARGA, "
                 + "R.TOTALREGISTROSPROCESADOS, R.RUTAARCHIVORESULTADO, to_char(r.fechacarga, 'DD/MM/YYYY hh:mi:ss') as FECHACARGASTR, R.FECHACARGA " +
                                                    " FROM SGTT_RTDOARCHIVOEF R WHERE R.IDENTIDADFEDERATIVA = ? " ;
         
         String AGREGA_ARCHIVO = "INSERT INTO SGTT_RTDOARCHIVOEF (IDENTIDADFEDERATIVA, NOMBREARCHIVOCARGA, "
                 + "TOTALREGISTROSARCHIVOCARGA, TOTALREGISTROSPROCESADOS, RUTAARCHIVORESULTADO, FECHACARGA) VALUES (?,?,?,?,'NULL',SYSDATE)";
         
         String EDITA_ARCHIVO = "UPDATE SGTT_RTDOARCHIVOEF SET NOMBREARCHIVOCARGA =?, TOTALREGISTROSARCHIVOCARGA = ?, "
                 + "TOTALREGISTROSPROCESADOS = ?, RUTAARCHIVORESULTADO = 'NULL', FECHACARGA = SYSDATE  WHERE IDENTIDADFEDERATIVA = ?";
         
         String EDITA_RUTA_ARCHIVO = "UPDATE SGTT_RTDOARCHIVOEF SET RUTAARCHIVORESULTADO = ? WHERE IDENTIDADFEDERATIVA = ?";
    
}
