package mx.gob.sat.siat.cob.seguimiento.dao.stdcob.sql;

import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.enums.EstadoDocumentoEnum;

public interface DocumentoSQL {

    String ACTUALIZAR_ESTATUS_DOCUMENTO_VIGILANCIA = "update sgtt_documento set ultimoestado= ? \n"
            + "where IDVIGILANCIA = ? AND IDENTIDADFEDERATIVA=?";
    String BITACORA_RECHAZO_VIGILANCIA_EF = "insert into sgtb_sgtdocumento (NUMEROCONTROL,IDESTADODOCTO,FECHAMOVIMIENTO )  "
            + "(select doc.numerocontrol," + EstadoDocumentoEnum.NO_PROCESADO.getValor() + ",sysdate FROM SGTT_DOCUMENTO doc where "
            + "idvigilancia=? and identidadfederativa=?)";
    String CONSULTA_MULTAS_PENDIENTES = "select doc.rfc,doc.NUMEROCONTROL,"
            + "obligacion.DESCRIPCION as descobligacion, "
            + "periodicidad.DESCRIPCIONPERIODO as descperiodo,\n"
            + "dvig.DESCRIPCION as descvig, \n"
            + "doc.FECHANOTIFICACION, "
            + "doc.FECHAVENCIMIENTODOCTO, \n"
            + "detalle.FECHACUMPLIMIENTO as fechapresentacionobligacion, "
            + "doc.ultimoestado as estadodocumento, "
            + "detalle.IDSITUACIONICEP as estadoicep, \n"
            + "periodicidad.mesinicio, "
            + "periodicidad.mesfin, detalle.ejercicio\n"
            + "from sgtt_documento doc \n"
            + "inner join sgtt_vigilancia vig on vig.idvigilancia=doc.idvigilancia\n"
            + "inner join SGTC_DSCRIPCIONVIG dvig on dvig.IDDESCRIPCION=vig.iddescripcion\n"
            + "inner join SGTT_DetalleDoc detalle on detalle.NUMEROCONTROL=doc.NUMEROCONTROL\n"
            + "inner join SGTA_PERIODICIDAD periodicidad on (detalle.IDPERIODO=periodicidad.IDPERIODO and detalle.IDPERIODICIDAD=periodicidad.IDPERIODICIDAD)\n"
            + "inner join SGTC_OBLIGACION obligacion on obligacion.IDOBLIGACION=detalle.IDOBLIGACION\n"
            + "where idEntidadFederativa = (select idEntidadFederativa from sgtp_usuarioef where usuario = ?)\n"
            + "and vig.idTipoMedio = 2\n"
            + "and detalle.idSituacionICEP in (0,1)\n";
    //+ "and fechaNotificacion between add_months(trunc(sysdate, 'MM'), -10) and trunc(sysdate) ";//valor numerico 10 de pruebas, deben ser 6 meses
    String CONSULTA_SECCIONADA = "select *  from\n"
            + "(select sgtt_documento.numerocontrol, sgtt_documento.numerocontrolpadre, \n"
            + "sgtt_documento.fechanotificacion, sgtt_documento.fechaimpresion,\n"
            + "sgtt_documento.rfc, sgtt_documento.boid, sgtt_documento.fechavencimientodocto,\n"
            + "sgtt_documento.idetapavigilancia, sgtt_documento.fechanolocalizadocontribuyente,\n"
            + "sgtt_documento.idvigilancia, sgtt_documento.esultimogenerado,sgtt_documento.ultimoestado,\n"
            + "sgtt_documento.fecharegistro from sgtt_documento )";
    String CONSULTA_X_NUMCONTROL = "select * from sgtt_documento doc, sgtt_vigilancia vig\n"
            + "where vig.idvigilancia = doc.idvigilancia\n"
            + "and numerocontrol = ? ";
    String CONSULTA_ESTADO_DOCTO_X_NUMCONTROL = "SELECT doc.numerocontrol,\n"
            + "  estado.idestadodocto,\n"
            + "  estado.nombre\n"
            + "FROM sgtt_documento doc\n"
            + "INNER JOIN sgtc_estadodocto estado\n"
            + "ON doc.ultimoestado = estado.idestadodocto\n"
            + "WHERE estado.idestadodocto IN (11,12,13,14,19)\n"
            + "and doc.numerocontrol = ";
    String UPDATE_CONSIDERA_RENUENCIA_DOCTO = "update sgtt_documento set sgtt_documento.considerarenuencia = 1\n"
            + "where numerocontrol = ";
    String ACTUALIZAR_ESTADO_DOCUMENTO_X_LOTE = "update SGTT_Documento set ultimoEstado = ?"
            + " where numeroControl in ("
            + " select numerocontrol"
            + " from"
            + " (select doc.numerocontrol, rownum rnum"
            + " from"
            + " (select doc.numerocontrol"
            + " from SGTT_DOCUMENTO doc"
            + " INNER JOIN SGTT_VIGILANCIA vig"
            + " ON doc.idvigilancia = VIG.idvigilancia"
            + " where vig.idvigilancia = ? and vig.idtipodocumento = ?"
            + " and doc.ultimoestado = ? and doc.fechavencimientodocto < TRUNC(sysdate) and doc.esultimogenerado=?"
            + " and doc.idetapavigilancia = ?"
            + " and doc.considerarenuencia = ?\n"
            + " order by doc.numerocontrol"
            + " ) doc"
            + " where rownum <= ?)"
            + " where rnum >= ?)";
    String CONSULTA_DOCUMENTOS_ACTUALIZADOS_X_LOTE = "select  *\n"
            + "from (\n"
            + "select  doc.* , rownum rowmin \n"
            + "  from (\n"
            + "    select distinct doc.numerocontrol, doc.rfc, doc.boid, doc.idetapavigilancia, doc.considerarenuencia, \n"
            + "    doc.fechanotificacion, doc.fechaimpresion, doc.fechavencimientodocto, doc.idadmonlocal, doc.fechanolocalizadocontribuyente, doc.fechanotrabajado,\n"
            + "    vig.idvigilancia, vig.idtipodocumento"
            + "    from SGTT_DOCUMENTO doc\n"
            + "          inner join SGTT_VIGILANCIA vig\n"
            + "             on doc.idvigilancia = vig.idvigilancia\n"
            + "          inner join SGTT_DETALLEDOC det \n"
            + "                           on (doc.numeroControl = det.numeroControl)\n"
            + "                        inner join SGTC_OBLIGACION obli\n"
            + "                           on (det.idobligacion = obli.idobligacion)"
            + "          where vig.idvigilancia = :idVigilancia and vig.idtipodocumento = :idTipoDocumento\n"
            + "          and doc.ultimoestado = :ultimoEstado and doc.fechavencimientodocto < TRUNC(sysdate) and doc.esultimogenerado = :esUltimoGenerado\n"
            + "          and doc.idetapavigilancia = :idEtapaVigilancia\n"
            + "          and doc.considerarenuencia = :consideraRenuencia \n"
            + "          and det.idsituacionicep = 0\n"
            + "                        and obli.aplicarenuentes in (:aplicaRenuentes)\n"
            + "         order by doc.numerocontrol\n"
            + "     ) doc\n"
            + "where rownum <= :limMayor )\n"
            + "where rowmin >= :limMenor";
    String CONSULTA_MONTO_TOTAL_MULTAS_BATCH = "select /*+index_ss(det) index_ss(ric) index_ss(mmo) */\n"
            + "  resol.numerocontrol, \n"
            + "  resol.numeroResolucion, \n"
            + "  resol.rfc, \n"
            + "  doc.boid, \n"
            + "  resol.idadmonlocalorigen as idclavesir, \n"
            + "  vig.idtipofirma, \n"
            + "  doc.fechanotificacion, \n"
            + "  resol.constanteresolmotivo, \n"
            + "  descuento.idmultadescuento,\n"
            + "  sum( mmo.monto) as idmultamonto\n"
            + "from sgtt_ResolucionDoc resol\n"
            + "  inner join SGTA_ResolICEP ric \n"
            + "    on resol.numeroResolucion = ric.numeroResolucion \n"
            + "    and resol.ultimoestado = 2 \n"
            + "    and resol.idresolucion is null\n"
            //            + "    and resol.monto is null\n" Descomentar despues de pruebas
            + "  inner join SGTT_DetalleDoc det \n"
            + "    on ric.numeroControl = det.numeroControl and ric.claveIcep = det.claveIcep\n"
            + "  inner join SGTC_MultaMonto mmo \n"
            + "      on mmo.idmultamonto = ric.idmultamonto \n"
            + "  inner join SGTT_Documento doc \n"
            + "    on det.numeroControl = doc.numeroControl\n"
            + "  inner join sgtt_vigilancia vig\n"
            + "    on doc.idvigilancia = vig.idvigilancia\n"
            + "    and vig.idVigilancia = #{jobParameters['idVigilancia']}\n"
            + "    and resol.idadmonlocalorigen = '#{jobParameters['idAdmonLocal']}' \n"
            + "  inner join sgtc_obligacion obl \n"
            + "    on det.idObligacion = obl.idObligacion\n"
            + "  inner join sgtc_multadscuento descuento\n"
            + "    on resol.constanteresolmotivo = descuento.constanteresolmotivo and descuento.fechafin is null\n"
            + "where mmo.constanteResolMotivo in ('RESOLMOTIVO_INCUMPLIMIENTO','RESOLMOTIVO_AMBOS') and (doc.fechaNotificacion >= mmo.fechaInicio)\n"
            + "and (doc.fechaNotificacion <= mmo.fechaFin or mmo.fechaFin is null)\n or \n"
            + "(mmo.constanteResolMotivo = 'RESOLMOTIVO_EXTEMPORANEIDAD' and (det.fechaCumplimiento >= mmo.fechaInicio)\n"
            + "and (det.fechaCumplimiento <= mmo.fechaFin or mmo.fechaFin is null))\n or \n"
            + "(mmo.constanteResolMotivo = 'RESOLMOTIVO_COMPLEMENTARIA' and (det.fechaPresentacionCompl >= mmo.fechaInicio)\n"
            + "and (det.fechaPresentacionCompl <= mmo.fechaFin or mmo.fechaFin is null))\n"
            + "group by \n"
            + "resol.numerocontrol, resol.numeroResolucion, resol.rfc, doc.boid, \n"
            + "resol.idadmonlocalorigen, vig.idtipofirma, doc.fechanotificacion, \n"
            + "resol.constanteresolmotivo, descuento.idmultadescuento";
    String CONSULTA_ICEPS_MULTA_BATCH = "select /*+index_ss(det) index_ss(ric) index_ss(mmo) */\n"
            + "  resol.numerocontrol, \n"
            + "  resol.numeroResolucion, \n"
            + "  doc.rfc, \n"
            + "  det.claveicep,\n"
            + "  doc.boid, \n"
            + "  doc.idadmonlocal as idclavesir, \n"
            + "  vig.idtipofirma, \n"
            + "  doc.fechanotificacion, \n"
            + "  resol.constanteresolmotivo, \n"
            + "  descuento.idmultadescuento,\n"
            + "  mmo.idmultamonto\n"
            + "from sgtt_ResolucionDoc resol\n"
            + "  inner join SGTA_ResolICEP ric \n"
            + "    on resol.numeroResolucion = ric.numeroResolucion \n"
            + "    and resol.ultimoestado = 2 \n"
            + "    and resol.idresolucion is null\n"
            + "  inner join SGTT_DetalleDoc det \n"
            + "    on ric.numeroControl = det.numeroControl and ric.claveIcep = det.claveIcep\n"
            + "  inner join SGTC_MultaMonto mmo \n"
            + "    on det.IdObligacion = mmo.IdObligacion and resol.constanteResolMotivo = mmo.constanteResolMotivo\n"
            + "  inner join SGTT_Documento doc \n"
            + "    on det.numeroControl = doc.numeroControl\n"
            + "  inner join sgtt_vigilancia vig\n"
            + "    on doc.idvigilancia = vig.idvigilancia\n"
            + "    and vig.idVigilancia = '#{jobParameters['idVigilancia']}'\n"
            + "    and doc.idAdmonLocal = '#{jobParameters['idAdmonLocal']}' \n"
            + "  inner join sgtc_obligacion obl \n"
            + "    on det.idObligacion = obl.idObligacion\n"
            + "  inner join sgtc_multadscuento descuento\n"
            + "    on resol.constanteresolmotivo = descuento.constanteresolmotivo and descuento.fechafin is null\n"
            + "    inner join cbzt_resolucion resolucion \n"
            + "      on resolucion.numresoluciondet = resol.numeroResolucion\n"
            + "      and resolucion.escargamasiva = 1\n"
            + "    join cbzc_unidadadmva ua \n"
            + "      on resolucion.idaudeterminante = ua.idunidadadmva \n"
            + "      and ua.idunidadmvatipo = 15 "
            + "where mmo.constanteResolMotivo in ('RESOLMOTIVO_INCUMPLIMIENTO','RESOLMOTIVO_AMBOS') and (doc.fechaNotificacion >= mmo.fechaInicio)\n"
            + "and (doc.fechaNotificacion <= mmo.fechaFin or mmo.fechaFin is null)\n or \n"
            + "(mmo.constanteResolMotivo = 'RESOLMOTIVO_EXTEMPORANEIDAD' and (det.fechaCumplimiento >= mmo.fechaInicio)\n"
            + "and (det.fechaCumplimiento <= mmo.fechaFin or mmo.fechaFin is null))\n or \n"
            + "(mmo.constanteResolMotivo = 'RESOLMOTIVO_COMPLEMENTARIA' and (det.fechaPresentacionCompl >= mmo.fechaInicio)\n"
            + "and (det.fechaPresentacionCompl <= mmo.fechaFin or mmo.fechaFin is null))";
    String CONSULTA_ICEPS_MULTA_CREDITO_BATCH = "select /*+index_ss(det) index_ss(ric) index_ss(mmo) */\n"
            + "  resol.numerocontrol, \n"
            + "  resol.numeroResolucion, \n"
            + "  doc.rfc, \n"
            + "  det.claveicep,\n"
            + "  doc.boid, \n"
            + "  resol.idadmonlocalorigen as idclavesir, \n"
            + "  vig.idtipofirma, \n"
            + "  doc.fechanotificacion, \n"
            + "  resol.constanteresolmotivo, \n"
            + "  descuento.idmultadescuento,\n"
            + "  mmo.idmultamonto\n"
            + "from sgtt_ResolucionDoc resol\n"
            + "  inner join SGTA_ResolICEP ric \n"
            + "    on resol.numeroResolucion = ric.numeroResolucion \n"
            + "    and resol.ultimoestado = 2 \n"
            + "    and resol.idresolucion is null\n"
            + "  inner join SGTT_DetalleDoc det \n"
            + "    on ric.numeroControl = det.numeroControl and ric.claveIcep = det.claveIcep\n"
            + "  inner join SGTC_MultaMonto mmo \n"
            + "    on det.IdObligacion = mmo.IdObligacion and resol.constanteResolMotivo = mmo.constanteResolMotivo \n"
            + "  inner join SGTT_Documento doc \n"
            + "    on det.numeroControl = doc.numeroControl\n"
            + "  inner join sgtt_vigilancia vig\n"
            + "    on doc.idvigilancia = vig.idvigilancia\n"
            + "    and vig.idVigilancia = #{jobParameters['idVigilancia']}\n"
            + "    and resol.idadmonlocalorigen = '#{jobParameters['idAdmonLocal']}' \n"
            + "  inner join sgtc_obligacion obl \n"
            + "    on det.idObligacion = obl.idObligacion\n"
            + "  inner join sgtc_multadscuento descuento\n"
            + "    on resol.constanteresolmotivo = descuento.constanteresolmotivo and descuento.fechafin is null\n"
            + "where mmo.constanteResolMotivo in ('RESOLMOTIVO_INCUMPLIMIENTO','RESOLMOTIVO_AMBOS') and (doc.fechaNotificacion >= mmo.fechaInicio)\n"
            + "and (doc.fechaNotificacion <= mmo.fechaFin or mmo.fechaFin is null)\n or \n"
            + "(mmo.constanteResolMotivo = 'RESOLMOTIVO_EXTEMPORANEIDAD' and (det.fechaCumplimiento >= mmo.fechaInicio)\n"
            + "and (det.fechaCumplimiento <= mmo.fechaFin or mmo.fechaFin is null))\n or \n"
            + "(mmo.constanteResolMotivo = 'RESOLMOTIVO_COMPLEMENTARIA' and (det.fechaPresentacionCompl >= mmo.fechaInicio)\n"
            + "and (det.fechaPresentacionCompl <= mmo.fechaFin or mmo.fechaFin is null))";
    String ACTUALIZAR_IDRESOLUCION_MULTA = "update sgtt_resoluciondoc\n"
            + "    set (idresolucion,numeroLoteCbz,numeroProcesoCbz,numeroEtapaCbz)=(\n"
            + "      select max(r.idresolucion),\n"
            + "        ltCbz.IDCMLOTE,\n"
            + "        ltCbz.IDPROCESO,\n"
            + "        ltCbz.IDPROCETAPA\n"
            + "      from CBZT_RESOLUCION r \n"
            + "        join ADMC_UNIDADADMVA ua \n"
            + "          on r.idaudeterminante = ua.idunidadadmva \n"
            + "          and UA.CLAVE_SIR='#{jobParameters['idAdmonLocal']}' \n"
            + "          and r.escargamasiva = 1\n"
            + "          and r.numresoluciondet = :numResolucionDet\n"
            + "        join CBZD_CMLOTE_RESOL ltCbz\n"
            + "          on ltCbz.IDRESOLUCION= r.IDRESOLUCION\n"
            + "        group by r.idresolucion,ltCbz.IDPROCESO,ltCbz.IDPROCETAPA,ltCbz.IDCMLOTE\n"
            + "        )\n"
            + "where numeroResolucion = :numResolucionDet\n"
            + "and ultimoestado = 2 \n"
            + "and idresolucion is null";
    String ACTUALIZAR_ULTIMOESTADO_MULTA = "update sgtt_resoluciondoc\n"
            + "set ultimoestado = 3, fechaenvioArca = to_date(:fechaRegistroARCA, 'yyyy/mm/dd HH24:mi:ss')\n"
            + "where numeroresolucion = :id \n"
            + "and ultimoestado = 2 \n"
            + "and idresolucion is null";
    String CONSULTAR_ICEPS_OMISOS = "SELECT NUMEROCONTROL,"
            + "CLAVEICEP,  "
            + "IDOBLIGACION,  "
            + "EJERCICIO,  "
            + "IDPERIODO,  "
            + "FECHAVENCIMIENTOOBLIGACION,  "
            + "FECHACUMPLIMIENTO,  "
            + "IDPERIODICIDAD,  "
            + "IDSITUACIONICEP,  "
            + "IDREGIMEN,  "
            + "IMPORTEPAGAR,  "
            + "IDTIPODECLARACION,  "
            + "TIENEMULTAEXTEMPORANEIDAD,  "
            + "TIENEMULTACOMPLEMENTARIA,  "
            + "IDCUMPLIMIENTO,  "
            + "IDCUMPLIMIENTOCOMPL,  "
            + "FECHAPRESENTACIONCOMPL,  "
            + "FECHABAJA  "
            + " FROM SGTT_DETALLEDOC  "
            + "WHERE NUMEROCONTROL = ? and FECHABAJA is null and FECHACUMPLIMIENTO is null";
    String CONSULTAR_ICEPS_X_LOTE = "SELECT \n"
            + "            DET.NUMEROCONTROL,\n"
            + "            DET.CLAVEICEP, \n"
            + "            DET.IDOBLIGACION, \n"
            + "            DET.EJERCICIO, \n"
            + "            DET.IDPERIODO,  \n"
            + "            DET.FECHAVENCIMIENTOOBLIGACION, \n"
            + "            DET.FECHACUMPLIMIENTO, \n"
            + "            DET.IDPERIODICIDAD, \n"
            + "            DET.IDSITUACIONICEP,\n"
            + "            DET.IDREGIMEN, \n"
            + "            DET.IMPORTEPAGAR,  \n"
            + "            DET.IDTIPODECLARACION\n"
            + "from SGTT_Documento doc\n"
            + "  inner join SGTT_DetalleDoc det \n"
            + "    on (doc.numeroControl = det.numeroControl)\n"
            + "    inner join SGTC_OBLIGACION obli\n"
            + "      on ( det.idobligacion = obli.idobligacion )\n"
            + "where doc.numeroControl in(\n"
            + "  select numerocontrol\n"
            + "    from\n"
            + "        (select doc.numerocontrol, rownum rowmin\n"
            + "          from\n"
            + "          (select doc.numerocontrol\n"
            + "            from SGTT_DOCUMENTO doc\n"
            + "            inner join SGTT_VIGILANCIA vig\n"
            + "            on doc.idvigilancia = vig.idvigilancia\n"
            + "            where vig.idvigilancia = :idVigilancia and vig.idtipodocumento = :idTipoDocumento \n"
            + "            and doc.ultimoestado = :ultimoEstado and doc.fechavencimientodocto < TRUNC(sysdate) and doc.esultimogenerado= :esUltimoGenerado \n"
            + "            and doc.idetapavigilancia = :idEtapaVigilancia\n"
            + "            and doc.considerarenuencia = :consideraRenuencia\n"
            + "            order by doc.numerocontrol\n"
            + "            ) doc\n"
            + "         where rownum <= :limMayor)\n"
            + "        where rowmin >= :limMenor\n"
            + ") and det.idSituacionIcep = 0 and           \n"
            + "obli.aplicarenuentes in (:aplicaRenuentes)\n"
            + "order by det.numerocontrol";
    String INSERTAR_ESTADOS_DOCUMENTOS_X_LOTE = "INSERT into sgtb_sgtdocumento\n"
            + "  SELECT numerocontrol, ?, ?\n"
            + "    from (select doc.numerocontrol, rownum rnum\n"
            + "        from\n"
            + "        (select doc.numerocontrol\n"
            + "          from SGTT_DOCUMENTO doc\n"
            + "          inner join SGTT_VIGILANCIA vig\n"
            + "          on doc.idvigilancia = VIG.idvigilancia\n"
            + "          where vig.idvigilancia = ? and vig.idtipodocumento = ?\n"
            + "          and doc.ultimoestado = ? and doc.fechavencimientodocto < TRUNC(sysdate) and doc.esultimogenerado=?\n"
            + "          and doc.idetapavigilancia = ?\n"
            + "          and doc.considerarenuencia = ?\n"
            + "          order by doc.numerocontrol\n"
            + "          ) doc\n"
            + "        where rownum <= ?)\n"
            + "    where rnum >= ?";
    String INSERTAR_ESTADOS_DOCUMENTO = "INSERT /*+ APPEND_VALUES */ INTO SGTB_SGTDOCUMENTO "
            + "(NUMEROCONTROL,IDESTADODOCTO,FECHAMOVIMIENTO) VALUES (?,?,sysdate)";
    String ACTUALIZAR_DOCUMENTO = "UPDATE SGTT_DOCUMENTO SET\n"
            + "FECHANOTIFICACION = ?,\n"
            + "FECHAIMPRESION = ?,\n"
            + "FECHAVENCIMIENTODOCTO = ?,\n"
            + "FECHANOLOCALIZADOCONTRIBUYENTE = ?,\n"
            + "ESULTIMOGENERADO = ?,\n"
            + "ULTIMOESTADO = ?,\n"
            + "CONSIDERARENUENCIA = ?,\n"
            + "FECHANOTRABAJADO = ?\n"
            + "WHERE NUMEROCONTROL = ?";
    String INSERT = "INSERT /*+ APPEND_VALUES */ INTO SGTT_DOCUMENTO "
            + "(NUMEROCONTROL,"
            + "NUMEROCONTROLPADRE,"
            + "FECHANOTIFICACION,"
            + "FECHAIMPRESION,"
            + "RFC,"
            + "BOID,"
            + "FECHAVENCIMIENTODOCTO,"
            + "IDETAPAVIGILANCIA,"
            + "FECHANOLOCALIZADOCONTRIBUYENTE,"
            + "IDVIGILANCIA,"
            + "ESULTIMOGENERADO,"
            + "ULTIMOESTADO,"
            + "FECHAREGISTRO,"
            + "CONSIDERARENUENCIA, "
            + "IDADMONLOCAL, "
            + "CODIGOPOSTAL, "
            + "IDCRH, "
            + "IDENTIDADFEDERATIVA, "
            + "IDTIPOPERSONA) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, sysdate, ?, ?, ?, ?, ?, ?)";
    /**
     * CONSLTA DEL TIPO DE DOCUMENTO
     */
    String TIPO_DOCUMENTO_NC = "SELECT V.IDTIPODOCUMENTO FROM SGTT_DOCUMENTO D "
            + "INNER JOIN SGTT_VIGILANCIA V ON D.IDVIGILANCIA = V.IDVIGILANCIA "
            + "WHERE NUMEROCONTROL = ?";
    String DOCUMENTO_NC = "SELECT * FROM SGTT_DOCUMENTO D "
            + "INNER JOIN SGTT_VIGILANCIA V ON D.IDVIGILANCIA = V.IDVIGILANCIA "
            + "WHERE NUMEROCONTROL = ?";
    String DOCUMENTOS_A_PROCESAR = "select documento.numerocontrol, \n"
            + "documento.numerocontrolpadre, \n"
            + "documento.fechanotificacion, \n"
            + "documento.fechaimpresion, \n"
            + "documento.rfc, \n"
            + "documento.boid, \n"
            + "documento.fechavencimientodocto, \n"
            + "documento.idetapavigilancia, \n"
            + "documento.fechanolocalizadocontribuyente, \n"
            + "documento.idvigilancia,  \n"
            + "documento.esultimogenerado, \n"
            + "documento.ultimoestado, \n"
            + "documento.fecharegistro, \n"
            + "documento.considerarenuencia, \n"
            + "documento.idadmonlocal, \n"
            + "vigilancia.idtipodocumento,\n"
            + "vigilancia.idtipomedio, \n"
            + "documento.identidadfederativa, \n"
            + "null as  FECHACARGAARCHIVOS,\n"
            + "null as  FECHANOTRABAJADO\n"
            + "from sgtt_documento documento  \n"
            + "join sgtt_vigilancia vigilancia on vigilancia.idvigilancia=documento.idvigilancia \n"
            + "and documento.ultimoestado in (:estados) \n"
            + "join sgtt_detalledoc detalledoc on detalledoc.NUMEROCONTROL = documento.NUMEROCONTROL\n"
            + "and detalledoc.idsituacionicep = 0 and detalledoc.FECHACUMPLIMIENTO is not null\n"
            + "group by documento.numerocontrol, \n"
            + "documento.numerocontrolpadre, \n"
            + "documento.fechanotificacion, \n"
            + "documento.fechaimpresion, \n"
            + "documento.rfc, \n"
            + "documento.boid, \n"
            + "documento.fechavencimientodocto, \n"
            + "documento.idetapavigilancia, \n"
            + "documento.fechanolocalizadocontribuyente, \n"
            + "documento.idvigilancia,  \n"
            + "documento.esultimogenerado, \n"
            + "documento.ultimoestado, \n"
            + "documento.fecharegistro, \n"
            + "documento.considerarenuencia, \n"
            + "documento.idadmonlocal, \n"
            + "documento.identidadfederativa, \n"
            + "vigilancia.idtipodocumento,\n"
            + "vigilancia.idtipomedio \n"
            + "order by numerocontrol";
    String DOCUMENTOS_A_PROCESAR_VIGILANCIA_LOCAL = "select documento.numerocontrol, \n"
            + "documento.numerocontrolpadre, \n"
            + "documento.fechanotificacion, \n"
            + "documento.fechaimpresion, \n"
            + "documento.rfc, \n"
            + "documento.boid, \n"
            + "documento.fechavencimientodocto, \n"
            + "documento.idetapavigilancia, \n"
            + "documento.fechanolocalizadocontribuyente, \n"
            + "documento.idvigilancia,  \n"
            + "documento.esultimogenerado, \n"
            + "documento.ultimoestado, \n"
            + "documento.fecharegistro, \n"
            + "documento.considerarenuencia, \n"
            + "documento.idadmonlocal, \n"
            + "vigilancia.idtipodocumento,\n"
            + "vigilancia.idtipomedio, \n"
            + "documento.identidadfederativa, \n"
            + "null as  FECHACARGAARCHIVOS,\n"
            + "null as  FECHANOTRABAJADO\n"
            + "from sgtt_documento documento  \n"
            + "join sgtt_vigilancia vigilancia on vigilancia.idvigilancia=documento.idvigilancia \n"
            + "and vigilancia.idvigilancia= :idVigilancia \n"
            + "and documento.idadmonlocal= :idAdmonlocal \n"
            + "and documento.ultimoestado in (:estados) \n"
            + "join sgtt_detalledoc detalledoc on detalledoc.NUMEROCONTROL = documento.NUMEROCONTROL\n"
            + "and detalledoc.idsituacionicep = 0 and detalledoc.FECHACUMPLIMIENTO is not null\n"
            + "group by documento.numerocontrol, \n"
            + "documento.numerocontrolpadre, \n"
            + "documento.fechanotificacion, \n"
            + "documento.fechaimpresion, \n"
            + "documento.rfc, \n"
            + "documento.boid, \n"
            + "documento.fechavencimientodocto, \n"
            + "documento.idetapavigilancia, \n"
            + "documento.fechanolocalizadocontribuyente, \n"
            + "documento.idvigilancia,  \n"
            + "documento.esultimogenerado, \n"
            + "documento.ultimoestado, \n"
            + "documento.fecharegistro, \n"
            + "documento.considerarenuencia, \n"
            + "documento.idadmonlocal, \n"
            + "documento.identidadfederativa, \n"
            + "vigilancia.idtipodocumento,\n"
            + "vigilancia.idtipomedio \n"
            + "order by numerocontrol";
    String GET_TIPO_DOCUMENTO_X_NUMCONTROL = "select doc.ultimoestado as IDESTADODOCTO, edo.nombre as NOMBRE  "
            + "from sgtt_documento doc "
            + "inner join sgtc_estadodocto edo on doc.ultimoestado = edo.idestadodocto "
            + "where doc.numerocontrol = ";
    String CONSULTA_DOCUMENTOS_POR_MOVIMIENTOS_EN_PADRON = "select documento.numerocontrol, \n"
            + "                   documento.numerocontrolpadre,\n"
            + "                   documento.fechanotificacion,\n"
            + "                   documento.fechaimpresion,\n"
            + "                   documento.rfc,\n"
            + "                   documento.boid,\n"
            + "                   documento.fechavencimientodocto,\n"
            + "                   documento.idetapavigilancia,\n"
            + "                   documento.fechanolocalizadocontribuyente,\n"
            + "                   documento.idvigilancia,\n"
            + "                   documento.esultimogenerado,\n"
            + "                   documento.ultimoestado,\n"
            + "                   documento.fecharegistro,\n"
            + "                   documento.considerarenuencia,\n"
            + "                   documento.fechanotrabajado,\n"
            + "                   documento.idadmonlocal,\n"
            + "                   documento.codigopostal,\n"
            + "                   documento.idcrh,\n"
            + "                   documento.identidadfederativa,\n"
            + "                   detalle_documento.claveicep, \n"
            + "                   detalle_documento.IDOBLIGACION, \n"
            + "                   detalle_documento.IDREGIMEN, \n"
            + "                   detalle_documento.EJERCICIO, \n"
            + "                   detalle_documento.IDPERIODO, \n"
            + "                   detalle_documento.IDPERIODICIDAD, \n"
            + "                   detalle_documento.FECHAVENCIMIENTOOBLIGACION, \n"
            + "                   detalle_documento.FECHABAJA, \n"
            + "                   detalle_documento.idsituacionicep, \n"
            + "                   padron.fechamantenimiento ,\n"
            + "                   vigilancia.idtipodocumento,\n"
            + "                   vigilancia.idtipomedio \n"
            + "            from sgtt_documento documento \n"
            + "            join sgtt_vigilancia vigilancia on vigilancia.idvigilancia=documento.idvigilancia\n"
            + "            join sgtt_detalledoc detalle_documento on documento.numerocontrol=detalle_documento.numerocontrol \n"
            + "            join sgtt_bajaicep padron on padron.boid=documento.boid and padron.claveicep=detalle_documento.claveicep";
    String CONSULTA_ESTADO_DOCUMENTO_NOTIFICADO_NO_LOCALIZADO = "select * from SGTC_ESTADODOCTO where idestadodocto in(4,5)";
    String CONSULTA_REGISTROS_BITACORA = "SELECT * FROM SGTB_SGTDOCUMENTO WHERE NUMEROCONTROL=? "
            + " AND IDESTADODOCTO IN (" + EstadoDocumentoEnum.NOTIFICADO.getValor() + "" + "," + EstadoDocumentoEnum.NO_LOCALIZADO.getValor() + "" + ") "
            + "ORDER BY FECHAMOVIMIENTO DESC";
    String ACTUALIZAR_DOCUMENTOS_ESULTIMOGENERADO = "update SGTT_Documento set esultimogenerado = :esultimogenerado\n"
            + "where numeroControl in (:documentos)";
    String INSERTAR_DOCUMENTOS = "INSERT INTO SGTT_DOCUMENTO (numerocontrol,\n"
            + "          numerocontrolpadre,\n"
            + "          fechanotificacion, \n"
            + "          fechaimpresion, \n"
            + "          rfc, \n"
            + "          boid, \n"
            + "          fechavencimientodocto, \n"
            + "          idetapavigilancia, \n"
            + "          fechanolocalizadocontribuyente,\n"
            + "          idvigilancia,\n"
            + "          esultimogenerado, \n"
            + "          ultimoestado,\n"
            + "          fecharegistro, \n"
            + "          considerarenuencia, \n"
            + "          fechanotrabajado, \n"
            + "          idadmonlocal,\n"
            + "          codigopostal,\n"
            + "          idcrh, \n"
            + "          identidadfederativa, \n"
            + "          idtipopersona)"
            + "          VALUES\n"
            + "          (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
    String ACTUALIZA_ESTADO_VIGILANCIA = "update SGTT_DOCUMENTO set ultimoestado=? where idvigilancia=?";
    String NUMERO_DETALLES_X_NUM_CONTROL = "SELECT \n"
            + "  count(1)\n"
            + "FROM (\n"
            + "  SELECT doc.NumeroControl\n"
            + "  FROM sgtt_documento doc\n"
            + "   JOIN sgtt_vigilancia vigilancia\n"
            + "          ON vigilancia.idvigilancia = doc.idvigilancia\n"
            + "          AND doc.NumeroControl = ?\n"
            + "   JOIN SGTT_PlantillaArca plantilla\n"
            + "          ON plantilla.idTipoDocumento = vigilancia.idTipoDocumento\n"
            + "          AND plantilla.idEtapaVigilancia = doc.idEtapaVigilancia\n"
            + "          AND plantilla.idTipoMedio = vigilancia.idTipoMedio\n"
            + "          AND plantilla.idTipoFirma = vigilancia.idTipoFirma\n"
            + "          AND plantilla.idNivelEmision = vigilancia.idNivelEmision\n"
            + "          AND plantilla.dias IS NULL\n"
            + "          AND plantilla.constanteResolMotivo IS NULL\n"
            + "          AND plantilla.fechafin IS NULL \n"
            + "          AND plantilla.esMulta = 0\n"
            + ") docto\n"
            + "  INNER JOIN sgtt_detalledoc detalleDocto\n"
            + "    ON docto.numerocontrol = detalleDocto.numerocontrol\n"
            + "    AND detalleDocto.idSituacionICEP = 0\n"
            + "  INNER JOIN sgtc_obligacion obligacion\n"
            + "    ON obligacion.idObligacion = detalleDocto.idObligacion\n"
            + "  INNER JOIN sgta_periodicidad periodicidad\n"
            + "    ON periodicidad.idperiodo = detalleDocto.idperiodo \n"
            + "    AND periodicidad.idperiodicidad = detalleDocto.idperiodicidad\n"
            + "  LEFT JOIN sgtc_FundamentoLeg fundamento\n"
            + "    ON fundamento.idObligacion = detalleDocto.idObligacion\n"
            + "    AND fundamento.idEjercicioFiscal = detalleDocto.ejercicio\n"
            + "    AND fundamento.idPeriodicidad = detalleDocto.idperiodicidad\n"
            + "    AND fundamento.idPeriodo = detalleDocto.idperiodo\n"
            + "    AND fundamento.fechaFin IS NULL";
    String UDAPATE_MONTO_TOTAL_RESOL_DOCTO = "UPDATE SGTT_RESOLUCIONDOC SET monto =  "
            + "WHERE numeroresolucion = ?";
    String ACTUALIZA_ESTADO_DOC = "update sgtt_documento set ultimoestado = ?, fechaEnvioARCA = null\n"
            + "     where numerocontrol in (\n"
            + "          select \n"
            + "             docto.numeroControl\n"
            + "          from sgtt_documento docto\n"
            + "              inner join SGTT_Vigilancia vig \n"
            + "                on docto.idVigilancia = vig.idVigilancia\n"
            + "              and vig.idVigilancia = ?\n"
            + "              and docto.idAdmonLocal = ?\n"
            + "              and docto.fechaEnvioARCA = to_date(?, 'yyyy/mm/dd HH24:mi:ss'))";
    /**
     * Recupera la informacion necesaria para generar un numero resolucion en
     * cobranza.
     */
    String SELECT_INFO_COBRANZA = "select /*+DRIVING_SITE(persona)*/ \n"
            + "  multaDocto.numeroResolucion,\n"
            + "  nvl(pf.RFC, pm.RFC) AS rfc,\n"
            + "  docto.boid AS boid,\n"
            + "  multaDocto.idAdmonLocalorigen AS idclavesir,\n"
            + "  vigilancia.idtipofirma, \n"
            + "  docto.fechanotificacion,\n"
            + "  multaDocto.constanteResolMotivo,\n"
            + "  descuento.idmultadescuento,\n"
            + "  multaDocto.monto,\n"
            + "  case docto.idTipoPersona\n"
            + "    when 'F' then 1 \n"
            + "    when 'M' then 2\n"
            + "  end as idTipoPersona,\n"
            + "  domicilio.idDomicilio\n"
            + "FROM sgtt_documento docto\n"
            + "  JOIN SGTT_ResolucionDoc multaDocto\n"
            + "    ON multaDocto.numerocontrol = docto.numerocontrol\n"
            + "    AND multaDocto.ultimoestado = 2\n"
            + "    AND multaDocto.idresolucion IS NULL\n"
            + "    AND docto.idVigilancia = #{jobParameters['idVigilancia']}\n"
            + "    AND multaDocto.idAdmonLocalorigen = '#{jobParameters['idAdmonLocal']}'\n"
            + "    AND multaDocto.monto is not null\n"
            + "  JOIN sgtt_vigilancia vigilancia\n"
            + "    ON vigilancia.idvigilancia = docto.idvigilancia\n"
            + "  JOIN sgtc_tipomedio tipoMedio\n"
            + "    ON tipoMedio.idTipoMedio = vigilancia.idTipoMedio\n"
            + "  JOIN sgtt_plantillaback plantilla\n"
            + "    ON plantilla.idTipoDocumento = vigilancia.idTipoDocumento\n"
            + "      AND plantilla.idEtapaVigilancia = docto.idEtapaVigilancia\n"
            + "      AND plantilla.idTipoMEdio = vigilancia.idTipoMedio\n"
            + "      AND plantilla.idTipoFirma = vigilancia.idTipoFirma\n"
            + "      AND plantilla.idNivelEmision = vigilancia.idNivelEmision\n"
            + "      AND plantilla.idCargoAdmtvo = vigilancia.idCargoAdmtvo\n"
            + "      AND plantilla.dias IS NULL\n"
            + "      AND plantilla.fechafin IS NULL\n"
            + "      AND plantilla.constanteResolMotivo = multadocto.constanteResolMotivo\n"
            + "      AND plantilla.esMulta = 1\n"
            + "  join sgtc_multadscuento descuento\n"
            + "    on multaDocto.constanteresolmotivo = descuento.constanteresolmotivo \n"
            + "      and descuento.fechafin is null\n"
            + "  JOIN rfcp_persona persona\n"
            + "    ON persona.idPersona=docto.boid  \n"
            + "  LEFT JOIN RFCP_PERSONAFISICA pf\n"
            + "    ON persona.idPersona = pf.idPersona   \n"
            + "  LEFT JOIN RFCP_PERSONAMORAL pm\n"
            + "    on persona.idPersona = pm.idPersona \n"
            + "  LEFT JOIN rfcc_catalogo catalogo\n"
            + "    on pm.idregimencapital = catalogo.idcatalogo\n"
            + "  LEFT JOIN (RFCP_DOMICILIO domicilio\n"
            + "    LEFT JOIN RFCC_ENTIDADFEDERA entidadFed\n"
            + "      ON entidadFed.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "    LEFT JOIN RFCC_COLONIA colonia       \n"
            + "      ON colonia.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "        AND colonia.IDMUNICIPIO = domicilio.IDMUNICIPIO\n"
            + "        AND colonia.IDCOLONIA = domicilio.IDCOLONIA\n"
            + "    LEFT JOIN RFCC_LOCALIDAD localidad\n"
            + "      ON localidad.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED\n"
            + "        AND localidad.IDMUNICIPIO = domicilio.IDMUNICIPIO\n"
            + "        AND localidad.IDLOCALIDAD = domicilio.IDLOCALIDAD\n"
            + "    LEFT JOIN RFCC_MUNICIPIO municipio\n"
            + "      ON municipio.CLAVEENTIDADFED = domicilio.CLAVEENTIDADFED \n"
            + "        AND municipio.IDMUNICIPIO = domicilio.IDMUNICIPIO)\n"
            + "    ON persona.idpersona = domicilio.IDPERSONA \n"
            + "    #{jobParameters['joinNivelEmision']}\n"
            + "WHERE domicilio.IDTIPODOMICILIO = '32'\n"
            + "  AND (domicilio.FECHAFINVIGENCIA > SYSDATE OR domicilio.FECHAFINVIGENCIA IS NULL) \n"
            + "  AND (domicilio.FECHACREACION = \n"
            + "    (SELECT MAX (B2S1.FECHACREACION)\n"
            + "      FROM RFCP_DOMICILIO B2S1\n"
            + "      WHERE B2S1.IDPERSONA = domicilio.IDPERSONA\n"
            + "        AND B2S1.IDTIPODOMICILIO = '32'\n"
            + "        AND B2S1.FECHAINICIOVIGENCIA <= SYSDATE\n"
            + "        AND (B2S1.FECHAFINVIGENCIA > SYSDATE OR B2S1.FECHAFINVIGENCIA IS NULL)) \n"
            + " OR domicilio.FECHAMODIFICACION IS NULL)\n"
            + "  AND(catalogo.fechafinvigencia > SYSDATE OR catalogo.fechafinvigencia IS NULL)";
}
