package mx.gob.sat.siat.cob.seguimiento.dao.stdcob.sql;

public interface EjecucionJobSQL {
    String CONSULTAR = " SELECT IDEJECUCION,IDPROCESO,INTENTO,FECHAINICIO,FECHAFIN,IDESTADOJOB,OBSERVACIONES " +
                       " FROM SGTB_EJECUCIONJOB WHERE 1 = 1 ORDER BY IDEJECUCION desc";
    String CONSULTAR_ULTIMA = "SELECT IDEJECUCION,IDPROCESO,INTENTO,FECHAINICIO,FECHAFIN,IDESTADOJOB,OBSERVACIONES" +
                       " FROM SGTB_EJECUCIONJOB WHERE IDPROCESO = ? AND IDEJECUCION = (SELECT MAX(IDEJECUCION) FROM SGTB_EJECUCIONJOB WHERE IDPROCESO = ? )";
    String INSERTAR = "INSERT INTO SGTB_EJECUCIONJOB (IDEJECUCION,IDPROCESO,INTENTO,FECHAINICIO,IDESTADOJOB,OBSERVACIONES) VALUES (SGTQ_EJECUCIONJOB.NEXTVAL,?,?,SYSDATE,?,?)";
    String ACTUALIZAR = "UPDATE SGTB_EJECUCIONJOB SET FECHAFIN = ?, IDESTADOJOB=?,INTENTO=?,OBSERVACIONES=? WHERE IDEJECUCION=?";
    String CONSULTAR_JOIN_INTENTO = " SELECT A.IDEJECUCION,A.IDPROCESO,B.INTENTO,A.FECHAINICIO,A.FECHAFIN,A.IDESTADOJOB,A.OBSERVACIONES,B.IDINTENTOJOB,B.INTENTO,B.FECHAINICIO AS FECHAINICIOINTENTO,B.FECHAFIN AS FECHAFININTENTO,B.OBSERVACIONES AS OBSERVACIONESINTENTO,B.IDESTADOJOB AS IDESTADOJOBINTENTO  "+
                                    " FROM SGTB_EJECUCIONJOB A INNER JOIN SGTB_INTENTOJOB B ON A.IDEJECUCION=B.IDEJECUCION WHERE 1 = 1 ";
    //para periodos mas cortos se prueba con: ej.fechafin < (sysdate + numtodsinterval(-24, 'HOUR'))
    //para el periodo que se usara en produccion es: add_months(sysdate,-1)
    String CONSULTAR_FECHA_ANTERIOR="select ej.*\n" +
                            " from SGTB_EJECUCIONJOB ej\n" +
                            " where\n" +
                            " ej.fechafin < add_months(sysdate,-1) \n" +
                            " and 0 in (\n" +
                            " select count(1) from SGTH_EjecucionJob hej where hej.IDEJECUCION = ej.IDEJECUCION\n" +
                            " )";
    String INSERTAR_HISTORICO = "INSERT INTO SGTH_EJECUCIONJOB (IDEJECUCION,IDPROCESO,INTENTO,FECHAINICIO,FECHAFIN,OBSERVACIONES,IDESTADOJOB) VALUES (?,?,?,?,?,?,?)";
    String BORRAR_REGISTRO="delete from SGTB_EJECUCIONJOB where IDEJECUCION = ?";
}
