package mx.gob.sat.siat.cob.seguimiento.dao.stdcob.sql;

/**
 *
 * @author christian.ventura
 */
public interface SgttResolucionDocSQL {

    String OBTENER_DATOS =
            "SELECT "
            + "TRIM(TO_CHAR(NVL(Z.CODIGOREGION,0),'00')) ALR, "
            + "trim(to_char(nvl(X.DESCRIPCION,0),'000')) AS CLAVECRH, "
            + "A.IDPERSONA as BOID, "
            + "datos.NUMEROCONTROL "
            + "FROM "
            + "( "
            + "select NUMERORESOLUCION, NUMEROCONTROL, boid "
            + "from (  "
            + "select /*+DRIVING_SITE(multa) DRIVING_SITE(documento) DRIVING_SITE(vigilancia) DRIVING_SITE(ric) DRIVING_SITE(det) DRIVING_SITE(monto) */ "
            + "multa.NUMERORESOLUCION, multa.NUMEROCONTROL, documento.boid, "
            + "nvl(monto.monto,0) as monto, case when monto.monto is null then 0 else 1 end as monto_disponible "
            + "from  "
            + "sgtt_resoluciondoc multa  "
            + "join sgtt_documento documento on multa.NUMEROCONTROL = documento.NUMEROCONTROL  "
            + "join sgtt_vigilancia vigilancia on documento.idvigilancia = vigilancia.idvigilancia "
            + "join SGTA_ResolICEP ric on (multa.numeroResolucion = ric.numeroResolucion)  "
            + "join SGTT_DetalleDoc det on ric.numeroControl = det.numeroControl and ric.claveIcep = det.claveIcep and det.numeroControl = documento.numeroControl  "
            + "left join SGTC_MultaMonto monto on (det.IdObligacion = monto.IdObligacion and multa.constanteResolMotivo = monto.constanteResolMotivo)   "
            + "and(  "
            + "(monto.constanteResolMotivo in ('RESOLMOTIVO_INCUMPLIMIENTO','RESOLMOTIVO_AMBOS') and (documento.fechaNotificacion >= monto.fechaInicio)  "
            + "and (documento.fechaNotificacion <= monto.fechaFin or monto.fechaFin is null))  "
            + "or  "
            + "(monto.constanteResolMotivo = 'RESOLMOTIVO_EXTEMPORANEIDAD' and (det.fechaCumplimiento >= monto.fechaInicio)  "
            + "and (det.fechaCumplimiento <= monto.fechaFin or monto.fechaFin is null))  "
            + "or  "
            + "(monto.constanteResolMotivo = 'RESOLMOTIVO_COMPLEMENTARIA' and (det.fechaPresentacionCompl >= monto.fechaInicio)  "
            + "and (det. fechaPresentacionCompl <= monto.fechaFin or monto.fechaFin is null))  "
            + ") "
            + "where  multa.ULTIMOESTADO = ? "
            + "and multa.FECHAREGISTRO = ? "
            + "and vigilancia.IDNIVELEMISION = ? "
            + "and vigilancia.IDCARGOADMTVO = ? "
            + "and vigilancia.IDTIPOMEDIO = ? "
            + "and vigilancia.IDTIPOFIRMA = ? "
            + "and multa.CONSTANTERESOLMOTIVO = ? "
            + "and multa.IDADMONLOCALORIGEN = ? "
            + ")  "
            + "group by NUMERORESOLUCION, NUMEROCONTROL, boid "
            + "having count(monto) = sum(monto_disponible) "
            + ") datos, "
            + "RFCP_DOMICILIO a "
            + "LEFT JOIN RFCC_REGION x "
            + "ON X.IDREGION = A.IDCRH "
            + "and X.IDTIPOREGION in (select IDCATALOGO "
            + "from RFCC_CATALOGO "
            + "WHERE TIPO='TIPOREGION' and CLAVEELEMENTO='CRH' and  "
            + "FECHAINICIOVIGENCIA<=SYSDATE AND (FECHAFINVIGENCIA>SYSDATE OR FECHAFINVIGENCIA IS NULL)) "
            + "left join (select CLAVEREGION,CODIGOREGION,DESCRIPCION "
            + "FROM RFCC_REGION@RFCD_DBLINK  "
            + "WHERE IDTIPOREGION IN "
            + "(select IDCATALOGO "
            + "from RFCC_CATALOGO@RFCD_DBLINK "
            + "WHERE TIPO='TIPOREGION' and CLAVEELEMENTO='ALR' and  "
            + "FECHAINICIOVIGENCIA<=SYSDATE AND (FECHAFINVIGENCIA>SYSDATE OR FECHAFINVIGENCIA IS NULL)) "
            + ") Z ON Z.CLAVEREGION = X.CLAVEPADRE "
            + "where "
            + "datos.boid = A.IDPERSONA "
            + "and A.IDTIPODOMICILIO = '32' "
            + "AND (A.FECHAFINVIGENCIA > SYSDATE OR A.FECHAFINVIGENCIA IS NULL) "
            + "AND (A.FECHACREACION =  "
            + "(SELECT MAX (B2S1.FECHACREACION) "
            + "FROM RFCP_DOMICILIO B2S1 "
            + "WHERE B2S1.IDPERSONA = A.IDPERSONA "
            + "AND B2S1.IDTIPODOMICILIO = '32' "
            + "AND B2S1.FECHAINICIOVIGENCIA <= SYSDATE "
            + "AND (B2S1.FECHAFINVIGENCIA > SYSDATE OR B2S1.FECHAFINVIGENCIA IS NULL)) OR A.FECHAMODIFICACION IS NULL) ";
    String UPDATE_RESOL = "update sgtt_resoluciondoc set idadmonlocalactual=?, idcrhactual=? where numerocontrol=?";
    String ACTUALIZA_ESTADO_RESOLUCION = "update sgtt_ResolucionDoc set ultimoestado = ?, fechaEnvioARCA = null\n"
            + "where numeroresolucion in (\n"
            + "      select \n"
            + "         resol.numeroResolucion\n"
            + "      from sgtt_ResolucionDoc resol\n"
            + "         inner join SGTT_Documento docto \n"
            + "           on resol.numeroControl = docto.numeroControl\n"
            + "         inner join SGTT_Vigilancia vig \n"
            + "           on docto.idVigilancia = vig.idVigilancia\n"
            + "           and vig.idVigilancia = ?\n"
            + "           and docto.idAdmonLocal = ?\n"
            + "           and resol.fechaEnvioARCA = to_date(?, 'yyyy/mm/dd HH24:mi:ss'))";
}
