/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.sat.siat.cob.seguimiento.dao.stdcob.sql;

import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.enums.EstadoDocumentoEnum;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.enums.NivelEmisionEnum;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.enums.SituacionVigilanciaEnum;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.enums.TipoMedioEnvioEnum;

/**
 *
 * @author root
 */
public interface VigilanciaAprobarSQL {

    String HEADER_COMUN = "select \n"
            + "                     v.idvigilancia as numero_carga,\n"
            + "                     dv.descripcion as descripcion_vigilancia ,\n"
            + "                     td.nombre as tipo_documento,\n"
            + "                     count(d.numerocontrol) as cantidad_documentos ,\n"
            + "                    tf.nombre as tipo_firma,\n"
            + "                    tf.idfirmatipo as id_firma,\n"
            + "                    v.fechacorte as fecha_corte,\n"
            + "                    v.fechacargaarchivos as fecha_carga,\n"
            + "                    v.numEmpleadoUsuario as numero_empleado,\n"
            + "                    tm.nombre as tipo_medio,\n"
            + "                    pa.descripcion as nombre_plantilla,\n"
            + "                    pa.idplantillaarca as id_plantilla,\n"
            + "                    max(val.fechaultimovalcumpl) fecha_validacion\n"
            + "             from sgtt_vigilancia v\n"
            + "             join SGTT_VIGILANCIAAL val on val.idvigilancia=v.idvigilancia\n"
            + "             join admc_firmatipo tf on tf.idfirmatipo=v.idtipofirma \n"
            + "             join sgtc_tipomedio tm on tm.idtipomedio=v.idtipomedio \n"
            + "             join sgtc_tipodocumento td on td.idtipodocumento=v.idtipodocumento \n"
            + "             join sgtt_documento d on d.idvigilancia=v.idvigilancia and d.idadmonlocal=val.idadmonlocal \n"
            + "             left join sgtt_plantillaarca pa on pa.idtipodocumento=v.idtipodocumento and \n"
            + "                                           pa.idetapavigilancia=d.idetapavigilancia and \n"
            + "                                           pa.idtipomedio= v.idtipomedio and \n"
            + "                                           pa.idnivelemision= v.idnivelemision and \n"
            + "                                           pa.idtipofirma= v.idtipofirma and \n"
            + "                                           pa.fechafin is null and "
            + "                                           pa.constanteresolmotivo is null and "
            + "                                           pa.esmulta=0 and"
            + "                                           pa.dias is null and"
            + "                                           v.idcargoadmtvo=pa.idcargoadmtvo\n"
            + "             join sgtc_dscripcionvig dv on dv.iddescripcion=v.iddescripcion \n"
            + "             where d.ultimoestado in("
            + EstadoDocumentoEnum.PENDIENTE_DE_PROCESAR.getValor() + ","
            + EstadoDocumentoEnum.CANCELADO.getValor() + ","
            + EstadoDocumentoEnum.CUMPLIDO_SIN_NOTIFICAR.getValor() + ","
            + EstadoDocumentoEnum.ANULADO.getValor() + ","
            + EstadoDocumentoEnum.CUMPLIDO.getValor() + ") and "
            + "                   val.idsituacionvigilancia=" + SituacionVigilanciaEnum.PENDIENTE_PROCESAR.getIdSituacion() + " and \n"
            + "                   v.idCargoAdmtvo=? and \n";

    String FOOTER_COMUN = "                   v.idtipomedio <> " + TipoMedioEnvioEnum.ENTIDAD_FEDERATIVA.getValor() + " \n"
            + "             group by  \n"
            + "                    fechacargaarchivos ,\n"
            + "                    v.fechacorte,\n"
            + "                    v.idtipofirma,\n"
            + "                    tf.nombre,\n"
            + "                    tf.idfirmatipo,\n"
            + "                    v.idvigilancia,\n"
            + "                    v.idtipodocumento,\n"
            + "                    td.nombre ,\n"
            + "                    v.numEmpleadoUsuario ,\n"
            + "                    dv.descripcion,\n"
            + "                    tm.nombre,\n"
            + "                    pa.idplantillaarca,\n"
            + "                    pa.descripcion"
            + " order by v.idvigilancia ";

    String CONSULTAR_TODAS = HEADER_COMUN
            + "                   v.idNivelEmision=" + NivelEmisionEnum.CENTRAL.getIdNivelEmision() + " and\n"
            + FOOTER_COMUN;

    String CONSULTAR_POR_LOCALIDAD = HEADER_COMUN
            + "                   v.idNivelEmision=" + NivelEmisionEnum.LOCAL.getIdNivelEmision() + " and\n"
            + "                   val.idadmonlocal=? and \n"
            + "                   d.idadmonlocal=?\n and "
            + FOOTER_COMUN;

    String CONSULTAR_VIGILANCIAS = "select \n"
            + "                     v.idvigilancia as numero_carga,\n"
            + "                     dv.descripcion as descripcion_vigilancia ,\n"
            + "                     td.nombre as tipo_documento,\n"
            + "                     count(d.numerocontrol) as cantidad_documentos ,\n"
            + "                    tf.nombre as tipo_firma,\n"
            + "                    tf.idfirmatipo as id_firma,\n"
            + "                    v.fechacorte as fecha_corte,\n"
            + "                    v.fechacargaarchivos as fecha_carga,\n"
            + "                    v.numEmpleadoUsuario as numero_empleado,\n"
            + "                    tm.nombre tipo_medio,\n"
            + "                    pa.descripcion as nombre_plantilla,\n"
            + "                    pa.idplantillaarca as id_plantilla,\n"
            + "                    val.idadmonlocal as id_admon_local,\n"
            + "                    al.descripcion as admon_local,\n"
            + "                    max(val.fechaultimovalcumpl) fecha_validacion\n"
            + "             from sgtt_vigilancia v\n"
            + "             join SGTT_VIGILANCIAAL val on val.idvigilancia=v.idvigilancia\n"
            + "             join sgtc_admonlocalsc al on al.idadmonlocal=val.idadmonlocal\n"
            + "             join admc_firmatipo tf on tf.idfirmatipo=v.idtipofirma \n"
            + "             join sgtc_tipomedio tm on tm.idtipomedio=v.idtipomedio \n"
            + "             join sgtc_tipodocumento td on td.idtipodocumento=v.idtipodocumento \n"
            + "             join sgtt_documento d on d.idvigilancia=v.idvigilancia and val.idadmonlocal=d.idadmonlocal \n"
            + "             left join sgtt_plantillaarca pa on pa.idtipodocumento=v.idtipodocumento and \n"
            + "                                           pa.idetapavigilancia=d.idetapavigilancia and \n"
            + "                                           pa.idnivelemision= v.idnivelemision and \n"
            + "                                           pa.idtipomedio= v.idtipomedio and \n"
            + "                                           pa.idtipofirma= v.idtipofirma and \n"
            + "                                           pa.fechafin is null and "
            + "                                           pa.constanteresolmotivo is null and "
            + "                                           pa.esmulta=0 and "
            + "                                           v.idcargoadmtvo=pa.idcargoadmtvo\n"
            + "             join sgtc_dscripcionvig dv on dv.iddescripcion=v.iddescripcion\n"
            + "             where d.ultimoestado in(0,11,7,18,16) and                    \n"
            + "                   val.idsituacionvigilancia=1 and \n"
            + "                   v.idtipomedio <> 2 \n"
            + "             group by  \n"
            + "                    fechacargaarchivos ,\n"
            + "                    v.fechacorte,\n"
            + "                    v.idtipofirma,\n"
            + "                    tf.nombre,\n"
            + "                    tf.idfirmatipo,\n"
            + "                    v.idvigilancia,\n"
            + "                    v.idtipodocumento,\n"
            + "                    td.nombre ,\n"
            + "                    v.numEmpleadoUsuario ,\n"
            + "                    dv.descripcion,\n"
            + "                    tm.nombre,\n"
            + "                    pa.descripcion,\n"
            + "                    pa.idplantillaarca,\n"
            + "                    val.idadmonlocal,\n"
            + "                    al.descripcion \n"
            + " order by v.idvigilancia,al.descripcion";
    
    String CONSULTA_CANTIDAD_VIGILANCIAS_AL = "select count(1) from ("
            + "                     select \n"
            + "                     v.idvigilancia as numero_carga,\n"
            + "                     dv.descripcion as descripcion_vigilancia ,\n"
            + "                     td.nombre as tipo_documento,\n"
            + "                     count(d.numerocontrol) as cantidad_documentos ,\n"
            + "                    tf.nombre as tipo_firma,\n"
            + "                    tf.idfirmatipo as id_firma,\n"
            + "                    v.fechacorte as fecha_corte,\n"
            + "                    v.fechacargaarchivos as fecha_carga,\n"
            + "                    v.numEmpleadoUsuario as numero_empleado,\n"
            + "                    tm.nombre tipo_medio,\n"
            + "                    pa.descripcion as nombre_plantilla,\n"
            + "                    pa.idplantillaarca as id_plantilla,\n"
            + "                    val.idadmonlocal as id_admon_local,\n"
            + "                    al.descripcion as admon_local,\n"
            + "                    max(val.fechaultimovalcumpl) fecha_validacion\n"
            + "             from sgtt_vigilancia v\n"
            + "             join SGTT_VIGILANCIAAL val on val.idvigilancia=v.idvigilancia\n"
            + "             join sgtc_admonlocalsc al on al.idadmonlocal=val.idadmonlocal\n"
            + "             join admc_firmatipo tf on tf.idfirmatipo=v.idtipofirma \n"
            + "             join sgtc_tipomedio tm on tm.idtipomedio=v.idtipomedio \n"
            + "             join sgtc_tipodocumento td on td.idtipodocumento=v.idtipodocumento \n"
            + "             join sgtt_documento d on d.idvigilancia=v.idvigilancia and val.idadmonlocal=d.idadmonlocal \n"
            + "             left join sgtt_plantillaarca pa on pa.idtipodocumento=v.idtipodocumento and \n"
            + "                                           pa.idetapavigilancia=d.idetapavigilancia and \n"
            + "                                           pa.idnivelemision= v.idnivelemision and \n"
            + "                                           pa.idtipomedio= v.idtipomedio and \n"
            + "                                           pa.idtipofirma= v.idtipofirma and \n"
            + "                                           pa.fechafin is null and "
            + "                                           pa.constanteresolmotivo is null and "
            + "                                           pa.esmulta=0 and "
            + "                                           v.idcargoadmtvo=pa.idcargoadmtvo\n"
            + "             join sgtc_dscripcionvig dv on dv.iddescripcion=v.iddescripcion\n"
            + "             where d.ultimoestado in(0,11,7,18,16) and                    \n"
            + "                   val.idsituacionvigilancia=1 and \n"
            + "                   v.idtipomedio <> 2 \n"
            + "             group by  \n"
            + "                    fechacargaarchivos ,\n"
            + "                    v.fechacorte,\n"
            + "                    v.idtipofirma,\n"
            + "                    tf.nombre,\n"
            + "                    tf.idfirmatipo,\n"
            + "                    v.idvigilancia,\n"
            + "                    v.idtipodocumento,\n"
            + "                    td.nombre ,\n"
            + "                    v.numEmpleadoUsuario ,\n"
            + "                    dv.descripcion,\n"
            + "                    tm.nombre,\n"
            + "                    pa.descripcion,\n"
            + "                    pa.idplantillaarca,\n"
            + "                    val.idadmonlocal,\n"
            + "                    al.descripcion \n"
            + " order by v.idvigilancia,al.descripcion)";
    
    String CONSULTA_VIGILANCIA_PAGINADA = "select * from ("
            + "                     select \n"
            + "                     v.idvigilancia as numero_carga,\n"
            + "                     dv.descripcion as descripcion_vigilancia ,\n"
            + "                     td.nombre as tipo_documento,\n"
            + "                     count(d.numerocontrol) as cantidad_documentos ,\n"
            + "                    tf.nombre as tipo_firma,\n"
            + "                    tf.idfirmatipo as id_firma,\n"
            + "                    v.fechacorte as fecha_corte,\n"
            + "                    v.fechacargaarchivos as fecha_carga,\n"
            + "                    v.numEmpleadoUsuario as numero_empleado,\n"
            + "                    tm.nombre tipo_medio,\n"
            + "                    pa.descripcion as nombre_plantilla,\n"
            + "                    pa.idplantillaarca as id_plantilla,\n"
            + "                    val.idadmonlocal as id_admon_local,\n"
            + "                    al.descripcion as admon_local,\n"
            + "                    max(val.fechaultimovalcumpl) fecha_validacion,\n"
            + "                    row_number() over(order by v.idvigilancia,al.descripcion) num \n"
            + "             from sgtt_vigilancia v\n"
            + "             join SGTT_VIGILANCIAAL val on val.idvigilancia=v.idvigilancia\n"
            + "             join sgtc_admonlocalsc al on al.idadmonlocal=val.idadmonlocal\n"
            + "             join admc_firmatipo tf on tf.idfirmatipo=v.idtipofirma \n"
            + "             join sgtc_tipomedio tm on tm.idtipomedio=v.idtipomedio \n"
            + "             join sgtc_tipodocumento td on td.idtipodocumento=v.idtipodocumento \n"
            + "             join sgtt_documento d on d.idvigilancia=v.idvigilancia and val.idadmonlocal=d.idadmonlocal \n"
            + "             left join sgtt_plantillaarca pa on pa.idtipodocumento=v.idtipodocumento and \n"
            + "                                           pa.idetapavigilancia=d.idetapavigilancia and \n"
            + "                                           pa.idnivelemision= v.idnivelemision and \n"
            + "                                           pa.idtipomedio= v.idtipomedio and \n"
            + "                                           pa.idtipofirma= v.idtipofirma and \n"
            + "                                           pa.fechafin is null and "
            + "                                           pa.constanteresolmotivo is null and "
            + "                                           pa.esmulta=0 and "
            + "                                           v.idcargoadmtvo=pa.idcargoadmtvo\n"
            + "             join sgtc_dscripcionvig dv on dv.iddescripcion=v.iddescripcion\n"
            + "             where d.ultimoestado in(0,11,7,18,16) and                    \n"
            + "                   val.idsituacionvigilancia=1 and \n"
            + "                   v.idtipomedio <> 2 \n"
            + "             group by  \n"
            + "                    fechacargaarchivos ,\n"
            + "                    v.fechacorte,\n"
            + "                    v.idtipofirma,\n"
            + "                    tf.nombre,\n"
            + "                    tf.idfirmatipo,\n"
            + "                    v.idvigilancia,\n"
            + "                    v.idtipodocumento,\n"
            + "                    td.nombre ,\n"
            + "                    v.numEmpleadoUsuario ,\n"
            + "                    dv.descripcion,\n"
            + "                    tm.nombre,\n"
            + "                    pa.descripcion,\n"
            + "                    pa.idplantillaarca,\n"
            + "                    val.idadmonlocal,\n"
            + "                    al.descripcion \n"
            + " order by v.idvigilancia,al.descripcion) \n"
            + "    where num>= ? and num< ?";
    
}
