package mx.gob.sat.siat.cob.seguimiento.dao.cobranza.sql;

public interface DiaInhabilSQL {

    String OBTEN_TODOS_DIA_INHABIL = "SELECT FECHA,MOTIVO FROM ADMC_DIAINHABIL WHERE FECHA >= ? AND IDENTIDAD IS NULL AND IDMUNICIPIO IS NULL AND IDUNIDADADMVA IS NULL AND ESRECAUDACION = 1 AND ESACTIVO = 1 AND (ESFESTIVO = 1 OR ESVACACION = 1 OR ESOFICERRADADH = 1)";
    String OBTEN_DIA_INHABIL_ANIO = "SELECT FECHA,MOTIVO FROM ADMC_DIAINHABIL WHERE FECHA >= ? AND TO_CHAR(SYSDATE,'YEAR') = TO_CHAR(FECHA,'YEAR')";
}
